README.rst

Details:
Embedding status images (bages) for
follwing facts:
- Version on Pypi
- Travis test status (master)
- Docs build status (latest)
- Test coverage (master)

Embed status images in front page

---

requirements.txt

When trying to upload a release to pypi,
the upload fails with  a
'ContextualVersionConflict: urllib3 1.22'.
This is fixed when we install a version
of urllib3 which is 1.21.1 or higer and
lower than 1.22.
Resolves #14

Fix ContextualVersionConflict problem

---

.gitignore

Reason for this is that playbooks look for their vars etc files
in their own directory, so playbooks for trying something out
need to be in the playbooks directory. The already existing
git exclusion of the /try directory is not sufficient for that.

Allow for try_* files to be ignored in git.

---

docs/changes.rst
docs/gen/zhmc_hba_module.rst
docs/gen/zhmc_nic_module.rst
docs/gen/zhmc_partition_module.rst
docs/gen/zhmc_virtual_function_module.rst
minimum-constraints.txt
requirements.txt
zhmc_ansible_modules/zhmc_hba.py
zhmc_ansible_modules/zhmc_nic.py
zhmc_ansible_modules/zhmc_partition.py
zhmc_ansible_modules/zhmc_virtual_function.py

Reason was that PR #21 uses functionality from the `six` package, and it seemed reasonable to use the version of `six` that is bundled with the Ansible Python module support (`ansible.module_utils` package). That drives the need to increase the Ansible minimum version from 2.0.0.1 to 2.2.0.0.
Analysis of the impact of this upgrade for some Linux distros:
* For RHEL/CentOS 7, Ansible 2.3 can be installed from the EPEL repo (see https://www.liquidweb.com/kb/how-to-install-ansible-on-centos-7-via-yum/).
* For Ubuntu, Ansible 2.3 can be installed from an Ansible PPA (see https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-ansible-on-ubuntu-14-04).

Increased minimum Ansible version to 2.2.0.0

---

docs/changes.rst
zhmc_ansible_modules/utils/__init__.py

Ready for review and merge.
This should also help with not reaching stopped status from a terminated status, or at least provide a better exception message.

Fixes #29: Fixed that a partition in terminated status can be deleted.

---

docs/gen/list_of_all_modules.rst
docs/gen/zhmc_adapter_module.rst
playbooks/create_hipersockets.yml
playbooks/delete_hipersockets.yml
playbooks/facts_adapter.yml
playbooks/set_adapter.yml
playbooks/set_matched_adapter.yml
zhmc_ansible_modules/zhmc_adapter.py

Has been tested manually.
Ready for review and use.
Includes support for adapter renaming via the "match" input parameter.
WIP, with these ToDos:
- Test change adapter type
- Test change crypto type

Fixes #83: Added support for managing Adapters

---

docs/changes.rst
zhmc_ansible_modules/zhmc_partition.py

Quickfix, therefore merging without review.

Adjusting empty ssc_ipv4_gateway property to None

---

docs/changes.rst
zhmc_ansible_modules/zhmc_adapter.py

Details:
* The crypto_number property is an integer property, and thus the Ansible
module needs to change the string passed by Ansible back to an integer.
It did that only for input properties, but not for the newly introduced
match parameter. This change applies the type conversions for all
properties now also for the match parameter.

Fixed adapter crypto_number property

---

docs/changes.rst
zhmc_ansible_modules/zhmc_cpc.py

Details:
* The dictionary to check input properties had the acceptable_status properts
written with a hyphen instead of underscore. This had the effect that it was rejected
as non-writeable when specifying it as input. This change fixes that.

Fixed a mispelled CPC property acceptable_status

---

zhmc_ansible_modules/zhmc_adapter.py

[MITIGATE] Mitigated issue with failing port retrieval

---

docs/gen/zhmc_adapter_module.rst
docs/gen/zhmc_cpc_module.rst
docs/gen/zhmc_crypto_attachment_module.rst
docs/gen/zhmc_hba_module.rst
docs/gen/zhmc_nic_module.rst
docs/gen/zhmc_partition_module.rst
docs/gen/zhmc_storage_group_attachment_module.rst
docs/gen/zhmc_storage_group_module.rst
docs/gen/zhmc_storage_volume_module.rst
docs/gen/zhmc_virtual_function_module.rst
tests/function/test_func_partition.py
tests/unit/test_hba.py
tests/unit/test_nic.py
tests/unit/test_partition.py
tests/unit/test_virtual_function.py
zhmc_ansible_modules/utils/__init__.py
zhmc_ansible_modules/zhmc_adapter.py
zhmc_ansible_modules/zhmc_cpc.py
zhmc_ansible_modules/zhmc_crypto_attachment.py
zhmc_ansible_modules/zhmc_hba.py
zhmc_ansible_modules/zhmc_nic.py
zhmc_ansible_modules/zhmc_partition.py
zhmc_ansible_modules/zhmc_storage_group.py
zhmc_ansible_modules/zhmc_storage_group_attachment.py
zhmc_ansible_modules/zhmc_storage_volume.py
zhmc_ansible_modules/zhmc_virtual_function.py

Renovate logging

---

Makefile
dev-requirements.txt
docs/changes.rst
minimum-constraints.txt
requirements.txt
tests/end2end/test_zhmc_partition.py
tests/end2end/utils.py

This depends on PR https://github.com/zhmcclient/python-zhmcclient/pull/573 in the zhmcclient project.

Added end2end testing, using zhmc_partition as first step

---

docs/changes.rst
zhmc_ansible_modules/zhmc_storage_group.py
zhmc_ansible_modules/zhmc_storage_volume.py
zhmc_ansible_modules/zhmc_user.py

These were reported by a new version of flake8 and were real errors.

Fixed issues with parameters in exception messages

---

docs/changes.rst
zhmc_ansible_modules/zhmc_nic.py

Rolls back PR #150 into 0.8.2.

0.8: Fixed ParameterError raised when creating NICs on CNA adapter ports

---

docs/changes.rst
zhmc_ansible_modules/zhmc_nic.py

Rolls back PR #158 into 0.8.3.

0.8: zhmc_nic: Updated definition of NIC properties to z15 and some z14 changes

---

docs/source/changes.rst
playbooks/get_cpc_io.md.j2
playbooks/get_cpc_io.yml
plugins/modules/zhmc_cpc.py
plugins/modules/zhmc_partition.py
tests/function/test_func_partition.py
tests/unit/test_partition.py

Rolls forward PR #162 into master/1.0.0.
No additional review needed.

Improvements in cpc and partition modules

---

minimum-constraints.txt
requirements.txt

Rolls back PR #180 into 0.8.3.
No further review needed.

0.8: Bumped cryptography to 3.2 on py36+

---

.travis.yml

Disabled failing test envs on py27/macos/min and pypy3

---

.travis.yml
dev-requirements.txt
docs_source/intro.rst
minimum-constraints.txt

At this point, it seems all issues have been fixed but the sanity test checks does not support python 3.9 yet.
Need to wait until it supports that.
Update: Disabled the sanity tests for Ansible 2.9 and Python 3.9 (or higher) because that combination is not supported by Ansible and is not likely to be added.

Added support for Python 3.9; Fixed an issue with installing typed-ast 

---

docs_source/development.rst

Ready for review, even though it still contains a few TBDs about the docs build on GutHub pages. We can finalize those once the docs build is established.

Updated development section

---

docs/changes.rst
docs/intro.rst

0.8: Docs: Increased supported Ansible versions to be 2.4 or higher

---

docs/changes.rst
playbooks/attach_crypto_byname.yml
zhmc_ansible_modules/zhmc_crypto_attachment.py

Since it is only a small enhancement, I suggest to add it to 0.8.x instead of bumping the minor version to 0.9.
The real life test on the latest update of this PR now succeeded.

0.8: Added support for adapter_names arg in zhmc_crypto_attachment module

---

plugins/modules/zhmc_adapter.py
plugins/modules/zhmc_cpc.py
plugins/modules/zhmc_crypto_attachment.py
plugins/modules/zhmc_hba.py
plugins/modules/zhmc_nic.py
plugins/modules/zhmc_partition.py
plugins/modules/zhmc_storage_group.py
plugins/modules/zhmc_storage_group_attachment.py
plugins/modules/zhmc_storage_volume.py
plugins/modules/zhmc_user.py
plugins/modules/zhmc_virtual_function.py
tests/sanity/ignore-2.10.txt

Fixed version_added fields for sanity test

---

.gitignore

0.8: Extended .gitignore with new docs build dirs from master

---

minimum-constraints.txt

Rolls back PR #324 into 0.8.4.

Fixed linked dep to coveralls-python with new pip version

---

docs/source/requirements.rst
docs/source/requirements_managed.rst

This is in response to issue 2 by Demetri.
This is still based on the current design with hosts=localhost, not using delegate_to. The use of delegate_to is left for a future PR.

Docs: Fixed and improved requirements section for control and managed nodes

---

docs/source/bibliography.rst
docs/source/release_notes.rst

Renamed "Bibliography" to "Resources" and removed common Ansible links

---

docs/source/modules/zhmc_adapter.rst
docs/source/modules/zhmc_cpc.rst
docs/source/modules/zhmc_crypto_attachment.rst
docs/source/modules/zhmc_hba.rst
docs/source/modules/zhmc_nic.rst
docs/source/modules/zhmc_partition.rst
docs/source/modules/zhmc_storage_group.rst
docs/source/modules/zhmc_storage_group_attachment.rst
docs/source/modules/zhmc_storage_volume.rst
docs/source/modules/zhmc_user.rst
docs/source/modules/zhmc_virtual_function.rst
docs/source/release_notes.rst
minimum-constraints.txt
plugins/module_utils/common.py
plugins/modules/zhmc_adapter.py
plugins/modules/zhmc_cpc.py
plugins/modules/zhmc_crypto_attachment.py
plugins/modules/zhmc_hba.py
plugins/modules/zhmc_nic.py
plugins/modules/zhmc_partition.py
plugins/modules/zhmc_storage_group.py
plugins/modules/zhmc_storage_group_attachment.py
plugins/modules/zhmc_storage_volume.py
plugins/modules/zhmc_user.py
plugins/modules/zhmc_virtual_function.py
requirements.txt
tests/unit/test_hba.py
tests/unit/test_nic.py
tests/unit/test_partition.py
tests/unit/test_virtual_function.py

I manually tested the new module input parameters in all variations and with several error cases.

Added support for verifying HMC certificates

---

docs/source/installation.rst
docs/source/release_notes.rst

Rolls back PR #409 into 0.9.2.

0.9: Docs: Stated that ansible-core 2.11 is supported

---

plugins/modules/zhmc_adapter.py
plugins/modules/zhmc_cpc.py
plugins/modules/zhmc_crypto_attachment.py
plugins/modules/zhmc_hba.py
plugins/modules/zhmc_nic.py
plugins/modules/zhmc_partition.py
plugins/modules/zhmc_storage_group.py
plugins/modules/zhmc_storage_volume.py
plugins/modules/zhmc_user.py
plugins/modules/zhmc_virtual_function.py

This PR accomodates the changes in zhmcclient to return the resource properties as an immutable DictView (PR https://github.com/zhmcclient/python-zhmcclient/pull/768).
This PR uses the version of zhmcclient prior to the DictView change. I have tested it locally with the DictView change.
**This is for review and discussion, not yet ready to merge.**

Accomodated DictView properties of zhmcclient

---

docs/source/release_notes.rst
plugins/modules/zhmc_adapter.py
plugins/modules/zhmc_cpc.py
plugins/modules/zhmc_crypto_attachment.py
plugins/modules/zhmc_hba.py
plugins/modules/zhmc_nic.py
plugins/modules/zhmc_partition.py
plugins/modules/zhmc_storage_group.py
plugins/modules/zhmc_storage_volume.py
plugins/modules/zhmc_user.py
plugins/modules/zhmc_virtual_function.py
tests/function/test_func_partition.py

This PR fixes the immutability accomodation in PR #395, which worked only with zhmcclient versions before immutability was introduced.

Fixed accomodation of immutable zhmcclient properties

---

docs/source/release_notes.rst
requirements.txt

Set to priority because a release with that fix should be made very quickly.

0.9: Pinned zhmcclient version to <0.31

---

docs/source/development.rst
docs/source/release_notes.rst

Small development docs fix that should still go into 0.10.0 before being released.
No further review needed.

Docs: Fixed instructions to release a version

---

docs/source/modules.rst

Docs: Split list of modules by CPC operational mode

---

docs/source/modules.rst
docs/source/modules/zhmc_lpar.rst
docs/source/release_notes.rst
minimum-constraints.txt
plugins/module_utils/common.py
plugins/modules/zhmc_lpar.py
requirements.txt
tests/function/test_func_lpar.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.9.txt

Particular review points are:
* the "state" values that are supported by the new zhmc_lpar module, and what they do. See their [description in the zhmc_lpar.py module](https://github.com/zhmcclient/zhmc-ansible-modules/blob/andy/lpar-module/plugins/modules/zhmc_lpar.py#L110).

Added zhmc_lpar module

---

docs/source/modules/zhmc_cpc.rst
docs/source/release_notes.rst
minimum-constraints.txt
plugins/modules/zhmc_cpc.py
requirements.txt
tests/function/test_func_cpc.py

Note, this PR requires corresponding support in the zhmcclient package, so it currently pulls in zhmcclient from the branch of PR https://github.com/zhmcclient/python-zhmcclient/pull/918, which is targeted for zhmcclient 1.2.0.

Added activation/deactivation to zhmc_cpc module

---

dev-requirements.txt

Pin voluptous<0.13.0 on Python 2.7; Increase sphinx-versions to 1.1.3.post-am2

---

.github/workflows/docs.yml
.github/workflows/test.yml
docs/source/development.rst
docs/source/release_notes.rst
galaxy.yml

Please approve the release of ibm_zhmc ansible collection 1.0.0 to Galaxy and AnsibleHub.
Link to change log: https://github.com/zhmcclient/zhmc-ansible-modules/blob/release_1.0.0/docs/source/release_notes.rst#version-100

Release 1.0.0

---

Makefile
docs/source/release_notes.rst
tests/end2end/test_zhmc_partition.py
tests/end2end/test_zhmc_user.py
tests/end2end/utils.py

Fixed end2end test concept and testcases

---

README.md

Disabled badge for AutomationHub version on README page

---

.github/workflows/test.yml
Makefile
docs/source/modules.rst
docs/source/modules/zhmc_password_rule.rst
docs/source/modules/zhmc_password_rule_list.rst
docs/source/release_notes.rst
minimum-constraints.txt
plugins/modules/zhmc_password_rule.py
plugins/modules/zhmc_password_rule_list.py
requirements.txt
tests/end2end/mocked_inventory.yaml
tests/end2end/mocked_vault.yaml
tests/end2end/mocked_z14_classic.yaml
tests/end2end/mocked_z14_dpm.yaml
tests/end2end/test_zhmc_partition.py
tests/end2end/test_zhmc_password_rule.py
tests/end2end/test_zhmc_password_rule_list.py
tests/end2end/test_zhmc_user.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.13.txt
tests/sanity/ignore-2.9.txt

Note: This PR is on top of PR #535. Review only the delta.
Merge only after PR #535 has been merged.

 Added new modules for password rules

---

docs/source/release_notes.rst
plugins/module_utils/common.py

Fixed that every module invocation created additional log handler

---

docs/source/release_notes.rst
plugins/module_utils/common.py
plugins/modules/zhmc_partition.py
tests/end2end/test_zhmc_partition.py
tests/function/test_func_partition.py
tests/unit/test_partition.py

Rolls back PR #557 into 1.1.2.
This PR was successfully end2end tested with test_zhmc_partition.py on: M12

1.1: zhmc_partition: Fixed check mode; fixed 'boot-storage-volume-name' in result

---

.github/workflows/test.yml
docs/source/release_notes.rst
tests/sanity/ignore-2.14.txt

This is considered a temporary disablement to get tests succeed again. See issue #579 for the overall issue.

Disabled Ansible sanity tests for py39/latest due to Ansible 7

---

dev-requirements.txt
docs/source/release_notes.rst

Rolls back PR #618 into 1.2.2.

1.2: Fixed sphinx-versions local fork to be PEP 440 compliant

---

.safety-policy.yml
ansible-constraints.txt
minimum-constraints.txt
requirements.txt

No rollback into 1.3.x needed, since safety was not invoked there.

Fixed safety issues 2023-04

---

docs/source/release_notes.rst
tests/end2end/test_zhmc_password_rule.py
tests/end2end/test_zhmc_user.py

Fixed bug when displaying end2end test details

---

.github/workflows/test.yml
docs/source/release_notes.rst
tools/os_setup.sh

The setup-python actions module removed Python 2.7, see https://github.com/actions/setup-python/issues/672
This PR circumvents that by using Python 2.7 from a Docker container, instead.

Circumvented removal of Python 2.7 support in setup-python action

---

docs/source/installation.rst

Rolls back PR #681 into 1.3.1.

1.3: Added Ansible 8 to the list of supported versions in docs

---

docs/source/modules/zhmc_storage_group.rst
docs/source/release_notes.rst
plugins/modules/zhmc_storage_group.py

I tested the new functionality, and it took 54 seconds to get a storage group with one volume over 8 zones fulfilled.
That is much faster than before.

Support for triggering LUN discovery

---

dev-requirements.txt
docs/source/release_notes.rst

Test: Circumvented a pip-check-reqs issue by excluding its version 2.5.0

---

dev-requirements.txt
docs/source/release_notes.rst

1.6: Test: Circumvented a pip-check-reqs issue by excluding its version 2.5.0

---

docs/source/release_notes.rst
tests/end2end/test_zhmc_adapter_list.py

I ran `TESTCASES=test_zhmc_adapter_list TESTHMC=A224 make end2end` against the HMC of the A224 system that previously failed the test (STG defect 1070648), and it now passes.

Test: Changed identification of adapters in end2end test to use PCHID

---

docs/source/release_notes.rst
tests/end2end/test_zhmc_adapter_list.py

Rolls back PR #739 into 1.6.1.

1.6: Test: Changed identification of adapters in end2end test to use PCHID

---

docs/source/release_notes.rst
minimum-constraints.txt
plugins/modules/zhmc_adapter.py
requirements.txt
tests/end2end/mocked_hmc_z14.yaml
tests/end2end/test_zhmc_adapter.py

1.6: zhmc_adapter: New props; Improved check mode for HS create; end2end tests

---

minimum-constraints.txt
requirements.txt

Rolls back PR #761 into 1.6.1.

1.6: Bump cryptography from 41.0.3 to 41.0.4 for Python>=3.7

---

.github/workflows/test.yml

Rolls back PR #770 into 1.6.1.

1.6: Moved 'make safety' to the end of the test workflow

---

CHANGELOG.rst
docs/source/release_notes.rst

This PR is an alternative to PR #732 that is compatible for the IBM unified documentation.

Added CHANGELOG.rst in a compatible way

---

docs/source/release_notes.rst
plugins/module_utils/common.py
plugins/modules/zhmc_hba.py
plugins/modules/zhmc_nic.py
plugins/modules/zhmc_partition.py
plugins/modules/zhmc_virtual_function.py
tests/end2end/test_zhmc_partition.py
tests/function/test_func_partition.py

Ran end2end tests against T224 with the latest commit 9390c86. Succeeded except for testcase "test_zhmc_partition_properties[hmc_definition=T224-type=ssc,state=active-check_mode=False]", which failed because starting the SSC partition resulted in status 'status-check'

Fixed that partitions in 'paused' status could not be stopped

---

docs/source/release_notes.rst
plugins/modules/zhmc_nic_list.py

Rolls back PR #791 into 1.7.1.

1.7: Fixed that 'name' property was missing in result of 'zhmc_nic_list'

---

Makefile
docs/source/modules/zhmc_lpar.rst
docs/source/release_notes.rst
minimum-constraints.txt
plugins/modules/zhmc_lpar.py
requirements.txt
tests/function/test_func_lpar.py

Fixed that zhmc_lpar reset_* waits for status operational

---

Makefile
docs/source/modules/zhmc_lpar.rst
docs/source/release_notes.rst
minimum-constraints.txt
plugins/modules/zhmc_lpar.py
requirements.txt
tests/function/test_func_lpar.py

Rolls back PR #802 into 1.7.1.
Needs to wait until that PR is approved - No further review needed on this PR.

1.7: Fixed that zhmc_lpar reset_* waits for status operational

---

.safety-policy.yml
minimum-constraints.txt
requirements.txt
tests/function/test_func_lpar.py

Rolls back PR #817 into 1.7.2.

1.7: Fixed missing 'operating-mode' in Image Profile setup for mocked LPAR fct tests

---

dev-requirements.txt
docs/source/release_notes.rst

Pinned voluptuous to <0.14 on Python<3.6

---

dev-requirements.txt
docs/source/release_notes.rst

Rolls back PR #823 into 1.7.2.

1.7: Pinned voluptuous to <0.14 on Python<3.6

---

docs/source/release_notes.rst
plugins/modules/zhmc_console.py
plugins/modules/zhmc_cpc.py

Fixed 'missing required arguments' in console/cpc upgrade

---

docs/source/release_notes.rst
plugins/modules/zhmc_console.py
plugins/modules/zhmc_cpc.py

Rolls back PR #835 into 1.7.2.

1.7: Fixed 'missing required arguments' in console/cpc upgrade

---

dev-requirements.txt
docs/source/modules.rst
docs/source/modules/zhmc_lpar_messages.rst
docs/source/modules/zhmc_partition_messages.rst
docs/source/release_notes.rst
minimum-constraints.txt
plugins/modules/zhmc_lpar_messages.py
plugins/modules/zhmc_partition_messages.py
requirements.txt
tests/end2end/test_zhmc_lpar_messages.py
tests/end2end/test_zhmc_partition_messages.py
tests/sanity/ignore-2.10.txt
tests/sanity/ignore-2.11.txt
tests/sanity/ignore-2.12.txt
tests/sanity/ignore-2.13.txt
tests/sanity/ignore-2.14.txt
tests/sanity/ignore-2.15.txt
tests/sanity/ignore-2.16.txt
tests/sanity/ignore-2.9.txt

Ready for review.
I ran the end2end tests for the new Ansible modules successfully on M96 (for LPAR) and on T224 (for DPM partitions).

Support for retrieving OS messages from LPARs and DPM partitions 

---

docs/source/release_notes.rst
tests/end2end/test_zhmc_cpc_list.py

Rolls back PR #866 into 1.7.4.

1.7: Fixed error in end2end test for zhmc_cpc_list module

---

docs/source/modules/zhmc_storage_group.rst
docs/source/release_notes.rst
plugins/modules/zhmc_storage_group.py

Rolls back PR #864 into 1.7.4.

1.7: Fixed KeyError in 'zhmc_storage_group' module for non-FCP groups

---

docs/source/modules/zhmc_adapter_list.rst
docs/source/modules/zhmc_lpar_list.rst
docs/source/modules/zhmc_partition_list.rst
docs/source/release_notes.rst
plugins/modules/zhmc_adapter_list.py
plugins/modules/zhmc_lpar_list.py
plugins/modules/zhmc_partition_list.py
tests/end2end/test_zhmc_adapter_list.py
tests/end2end/test_zhmc_partition_list.py

* The various checks in the adapter, partition, lpar modules on HMC version or HMC API version.
* The treatment of the additional_properties parameter in the adapter and partition modules.
**End2end tests:**
I ran the end2end test with TESTCASES="test_zhmc_adapter_list or test_zhmc_partition_list" on the following DPM systems and they all succeeded:
* M12 (HMC 2.14)
* T224 (HMC 2.15)
* A224 (HMC 2.16 with API version 4.10)
I did not have an HMC 2.16 with API version 4.1 or 4.2 (that case is treated differently by the code).
The code changes in test_zhmc_lpar_list were just to improve the log messages - I did not run an end2end test for that module.

Fixed zhmc_adapter_list and zhmc_partition_list on HMC 2.14 and 2.15

---

docs/source/modules/zhmc_adapter_list.rst
docs/source/modules/zhmc_lpar_list.rst
docs/source/modules/zhmc_partition_list.rst
docs/source/release_notes.rst
plugins/modules/zhmc_adapter_list.py
plugins/modules/zhmc_lpar_list.py
plugins/modules/zhmc_partition_list.py
tests/end2end/test_zhmc_adapter_list.py
tests/end2end/test_zhmc_partition_list.py

Rolls back PR #854 into 1.7.4.

1.7: Fixed zhmc_adapter_list and zhmc_partition_list on HMC 2.14 and 2.15

---

docs/source/modules/zhmc_adapter_list.rst
docs/source/modules/zhmc_lpar_list.rst
docs/source/modules/zhmc_partition_list.rst
plugins/modules/zhmc_adapter_list.py
plugins/modules/zhmc_lpar_list.py
plugins/modules/zhmc_partition_list.py

Came up during review of PR #853

Fixed misspelling 'preferrable'

---

ansible-constraints.txt

Has been fixed for 1.8.0 in release PR #896

1.7: Fixed constraint for MarkupSafe in ansible-constraints.txt

---

Makefile
docs/source/release_notes.rst
minimum-constraints.txt
plugins/modules/zhmc_lpar_list.py
requirements.txt
tests/end2end/test_zhmc_lpar_list.py
tests/end2end/test_zhmc_partition_list.py

End2end tests (with zhmcclient stable_1.13 as of PR 1422):
* Classic mode: `TESTHMC=M96 TESTCASES=test_zhmc_lpar_list.py make end2end` passed (slow additional_properties with HMC 2.15)
* Classic mode: `TESTHMC=A01 TESTCASES=test_zhmc_lpar_list.py make end2end` passed (fast additional_properties with HMC 2.16 GA 1.5)
* DPM mode: `TESTHMC=T224 TESTCASES=test_zhmc_partition_list.py make end2end` passed.

Fixed performance issue with zhmc_lpar/partition_list 

---

docs/source/release_notes.rst
minimum-constraints.txt
requirements.txt

Rolls back PR #925 into 1.8.3.

1.8: Bump cryptography minimum version to 42.0.2

---

Makefile
docs/source/release_notes.rst

Details:
* Added a new make target end2end_show which can be used to view the HMCs defined for the end2end tests. (issue #888)

Added make target end2end_show 

---

docs/source/release_notes.rst
plugins/modules/zhmc_partition.py

When running playbook partition_nodb_create.yml with linux partition input - playbook is failing when mounting iso to the partition
During investigation - we have checked BufferedReader class - it supports read() but it didn’t support readall()
https://docs.python.org/3/library/io.html#io.BufferedReader
Later we modified ensure_iso_mount to use BufferedReader.read() instead of BufferedReader.readall()
Created jira [IAUT-1151](https://jsw.ibm.com/browse/IAUT-1151) for the same - Please do review once & merge the code

Fixed AttributeError in ensure_iso_mount function of zhmc_partition 

---

.github/workflows/test.yml
docs/source/release_notes.rst

Rolls back PR #951 into 1.8.4.

1.8: Fixed macos version used in test workflow for py35/36/37

---

.github/workflows/test.yml
docs/source/installation.rst
docs/source/release_notes.rst

I have opened https://github.com/actions/setup-python/issues/866 for that. This change allows us to have successful test runs without a fix for that. Once we get a fix, we can revert this PR.
Note that this change does not drop the support for Python 3.5. It is still "best can do".

Dropped test runs on Python 3.5

---

.github/workflows/test.yml
docs/source/installation.rst
docs/source/release_notes.rst

PR #961 dropped the test runs for Python 3.5 in order to address the Pip certificate issue on Github Actions with Python 3.5. 
A comment in https://github.com/actions/setup-python/issues/866 suggested a circumvention. This PR reverts the dropping of test support and uses that circumvention.

Re-established test runs on Python 3.5 and circumvented pip cert issue

---

.github/workflows/test.yml
docs/source/installation.rst
docs/source/release_notes.rst

Rolls back PR #963 into 1.8.4.

1.8: Re-established test runs on Python 3.5 and circumvented pip cert issue 

---

docs/source/release_notes.rst
plugins/module_utils/common.py
plugins/modules/zhmc_user.py

Changes:
- Obscure 'password' property in log messages.
Fixes https://github.com/zhmcclient/zhmc-ansible-modules/issues/967

Obscure password in log messages

---

plugins/modules/zhmc_user.py

PR that introduced the errors: #970
Example of the prior error in the end2end_mocked tests for that PR: https://github.com/zhmcclient/zhmc-ansible-modules/actions/runs/9535584752/job/26281487052#step:19:2482
I did not find them in the review, and I did not look at the end2end_mocked test results which clearly showed the error. Because of other errors currently in these tests, a non-zero exit code of that test is currently tolerated in the test workflow.

Fixed recently introduced errors in zhmc_user module

---

Makefile
docs/source/installation.rst
docs/source/release_notes.rst
meta/runtime.yml

This is needed to pass the ansible-lint test on Ansible Automation Hub.

Increased minimum Ansible version to Ansible 8 / ansible-core 2.15

---

Makefile
docs/source/installation.rst
docs/source/release_notes.rst
meta/runtime.yml

Rolls back PR #988 into 1.8.4.
No additional review needed.

1.8: Increased minimum Ansible version to Ansible 8 / ansible-core 2.15

---

docs/source/modules.rst
docs/source/modules/zhmc_versions.rst
docs/source/release_notes.rst
plugins/modules/zhmc_versions.py
tests/end2end/test_zhmc_versions.py
tests/sanity/ignore-2.14.txt
tests/sanity/ignore-2.15.txt
tests/sanity/ignore-2.16.txt
tests/sanity/ignore-2.17.txt

Link to RST source of docs page for new module: https://github.com/zhmcclient/zhmc-ansible-modules/blob/andy/versions-module/docs/source/modules/zhmc_versions.rst
* Should the CPCs be filtered, as currently implemented
* Should the CPC Firmware Features not be returned, as currently implemented (that would require "Get CPC Properties")

Added zhmc_versions module

---

.github/workflows/test.yml
docs/source/release_notes.rst

Removed Python 3.13-beta1 again from tests

---

minimum-constraints-develop.txt
plugins/module_utils/common.py
requirements-develop.txt
tests/unit/test_common.py

This is intended to be used for consolidating all the conversions between hyphenized and underscored property names in the modules.

Added common functions for hyphen-underscore property name conversions

---

docs/source/release_notes.rst
tests/end2end/test_zhmc_password_rule.py

Test: Fixed exception handling in end2end tests for password rules

---

docs/source/bibliography.rst
docs/source/modules.rst
docs/source/modules/zhmc_user_pattern.rst
docs/source/modules/zhmc_user_pattern_list.rst
docs/source/release_notes.rst
plugins/modules/zhmc_user_pattern.py
plugins/modules/zhmc_user_pattern_list.py
tests/end2end/mocked_hmc_z14.yaml
tests/end2end/mocked_hmc_z16.yaml
tests/end2end/test_zhmc_user_pattern.py
tests/end2end/test_zhmc_user_pattern_list.py
tests/sanity/ignore-2.14.txt
tests/sanity/ignore-2.15.txt
tests/sanity/ignore-2.16.txt
tests/sanity/ignore-2.17.txt

Note, the end2end_mocked test has some new failures because https://github.com/zhmcclient/python-zhmcclient/pull/1582 is not yet merged. In a local test with that PR, there were no new failures.
* These new modules return their properties with underscores in the property names.

Added user_pattern and user_pattern_list modules

---

docs/source/release_notes.rst
tests/end2end/test_zhmc_user.py

Note: This PR requires PR https://github.com/zhmcclient/python-zhmcclient/pull/1584. Not having that PR in the test workflow is why the new end2end testcases have failures in "make end2end_mocked". I have tested it locally with that PR.
Update: I have now re-run the test workflow with PR https://github.com/zhmcclient/python-zhmcclient/pull/1584 merged, and now the new testcases in the end2end_mocked tests pass.

Test: Added end2end tests for adding and removing user roles to/from users

---

docs/source/bibliography.rst
docs/source/modules.rst
docs/source/modules/zhmc_cpc_capacity.rst
docs/source/release_notes.rst
plugins/modules/zhmc_cpc_capacity.py
tests/end2end/mocked_hmc_z16.yaml
tests/end2end/test_zhmc_cpc_capacity.py
tests/sanity/ignore-2.14.txt
tests/sanity/ignore-2.15.txt
tests/sanity/ignore-2.16.txt
tests/sanity/ignore-2.17.txt

Re-implemented the module since the last review.
Requires a full re-review.
* This new module returns its properties with underscores in the property names.
Worked through answers on channel: https://ibm-systems-z.slack.com/archives/C3XE4H56X/p1707739938954879
Tests (on 2024-07-03 with commit cf21ce7):
* Ran the new end2end testcase for state=facts for A224 - passed
* Manually ran a test playbook for state=facts for A224 - had the expected result values
* Manually ran a test playbook for state=set in check mode for A224 - showed the expected changes
* Manually ran a test playbook for state=set in non-check mode for A224 - showed reasonable errors for the non-existing capacity record.

Added zhmc_cpc_capacity module

---

README.md
docs/source/development.rst
docs/source/installation.rst
docs/source/release_notes.rst

The layout follows the [README.md file from the z/OS core collection](https://github.com/ansible-collections/ibm_zos_core/blob/staging-v1.10.0-release-tasks/README.md)
Link to the rendered versions
* README.md: https://github.com/zhmcclient/zhmc-ansible-modules/blob/andy/new-readme-content/README.md
* Support matrix: https://github.com/zhmcclient/zhmc-ansible-modules/blob/andy/new-readme-content/docs/source/installation.rst#support-matrix

Adjusted README to new AutomationHub requirements

---

docs/source/modules/zhmc_lpar_messages.rst
docs/source/modules/zhmc_partition_messages.rst
plugins/modules/zhmc_lpar_messages.py
plugins/modules/zhmc_partition_messages.py

Fixed doc typos in 'zhmc_lpar_messages' and 'zhmc_partition_messages'

---

docs/source/modules.rst
docs/source/modules/zhmc_lpar_command.rst
docs/source/modules/zhmc_partition_command.rst
docs/source/release_notes.rst
plugins/module_utils/common.py
plugins/modules/zhmc_lpar_command.py
plugins/modules/zhmc_partition_command.py
tests/end2end/test_zhmc_lpar_command.py
tests/end2end/test_zhmc_partition_command.py
tests/sanity/ignore-2.14.txt
tests/sanity/ignore-2.15.txt
tests/sanity/ignore-2.16.txt
tests/sanity/ignore-2.17.txt

Has been tested with:
* z/VM LPAR ZVM01 on M96 (classic mode)
* Approach for waiting for the end of the command output lines

Added new modules for executing OS console commands

---

.safety-policy-develop.yml
.safety-policy-install.yml
minimum-constraints-develop.txt
minimum-constraints-install.txt
requirements.txt

Rolls back PR #1050 into 1.9.2.

1.9: Cleaned up safety files; Increased ansible-core/packaging versions

---

Makefile
docs/source/release_notes.rst

Rolls back PR #1062 into 1.9.2.

1.9: Fixed removal of some files in Makefile

---

docs/source/release_notes.rst
plugins/module_utils/common.py
plugins/modules/zhmc_user.py
tests/end2end/test_zhmc_user.py
tests/unit/test_common.py

I tested that the new checks in the end2end test for zhmc_user now catches the error, and that the fix passes the new test.

Fixed password blanked in zhmc_user module

---

.github/workflows/test.yml
Makefile
docs/source/bibliography.rst
docs/source/conf.py
docs/source/index.rst
docs/source/installation.rst
docs/source/playbooks.rst
docs/source/release_notes.rst
docs/source/requirements.rst

Fixed broken/redirected links; Added linkcheck to test workflow

---

docs/source/conf.py
docs/source/release_notes.rst

Docs: Ignored www.ansible.com in linkcheck, because it occasionally times out

---

docs/source/conf.py
docs/source/release_notes.rst

Rolls back PR #1091 into 1.9.3.

1.9: Docs: Ignored www.ansible.com in linkcheck, because it occasionally times out

---

docs/source/release_notes.rst
tests/end2end/mocked_hmc_z14.yaml
tests/end2end/mocked_hmc_z16.yaml

Rolls back PR #1098 into 1.9.4.

1.9: Fixed duplicate 'description' property in test YAML files

---

.safety-policy-install.yml
docs/source/release_notes.rst
minimum-constraints-install.txt
requirements.txt

Addressed safety issues up to 2024-12-29

---

docs/source/release_notes.rst
plugins/modules/zhmc_nic.py

1.9: Circumvention for HTTP error 500.12 when creating Hipersocket NICs

---

docs/source/modules/zhmc_user.rst
docs/source/modules/zhmc_user_list.rst
docs/source/release_notes.rst
plugins/module_utils/common.py
plugins/modules/zhmc_user.py
plugins/modules/zhmc_user_list.py
tests/end2end/test_zhmc_user.py
tests/end2end/test_zhmc_user_list.py

This PR started out as an idea for improving the performance of getting a user list with all properties and names for any referenced objects (instead of their URIs). So far, that is done by listing the users with the zhmc_user_list module, and then looping through the resulting users to retrieve their facts with the zhmc_user module, which adds artificial properties for the names of referenced objects. That causes each invocation of the zhmc_user to list the 7 possible kinds of referenced objects for the name lookup, and is slow. The solution implemented in this PR is an "expand_names" parameter for the zhmc_user_list module, which allows getting the names for any referenced objects in one invocation of the module. The module then performs only a single listing of the possible kinds of …

Added expand_names and fixes for zhmc_user, zhmc_user_list

---

docs/source/release_notes.rst
plugins/modules/zhmc_nic.py

Tested in dal10z4 with partition CPCA.dal1-qz2-sr1-rk123-s02

Circumvention for HTTP error 500.12 when creating Hipersocket NICs

---

docs/source/release_notes.rst
tests/end2end/test_zhmc_partition.py

1.9: Speed up end2end test test_zhmc_partition_properties()

---

docs/source/release_notes.rst
requirements-develop.txt

1.9: Circumvented safety issue with import of typer module

---

docs/source/release_notes.rst
minimum-constraints-develop.txt
requirements-develop.txt

* Typer version was pinned to 0.17.0 due to pyupio/safety#778
* The issue is fixed with safety 3.6.1
* We no longer need to pin that version

Removed the pinning on typer version <0.17.0 with safety 3.6.1

---

docs/source/release_notes.rst
minimum-constraints-develop.txt
requirements-develop.txt

1.9: Removed the pinning on typer version <0.17.0 with safety 3.6.1

---

docs/source/release_notes.rst
minimum-constraints-develop.txt

1.9: Upgrade nltk to 3.9.1 to make it compatible with safety 3.6.1

---

docs/source/release_notes.rst
minimum-constraints-install.txt
plugins/modules/zhmc_lpar_messages.py
plugins/modules/zhmc_partition_messages.py
requirements.txt

Tested with local `try_playbooks/partition_messages.yml` playbook on AHPS with a modified partition_messages module that adds an HMC timestamp for `datetime.now()` in UTC, if no timestamp is returned from the HMC. Verified that the version before the change (using `pytz.utc`) has the correct result, as well as the version with the change (using `timezone.utc`).
Here is the modification to the partition_messages module for the test:
```
--- a/plugins/modules/zhmc_partition_messages.py
+++ b/plugins/modules/zhmc_partition_messages.py
@@ -348,10 +348,14 @@ def perform_os_messages(params):
result = []
for os_message in result_dict['os-messages']:
hmc_ts = os_message.get('timestamp')
+            if hmc_ts == -1:
+                from …
```

Removed use of pytz package

---

Makefile
docs/source/release_notes.rst
minimum-constraints-install.txt
requirements-ansible.txt
requirements.txt

Moved ansible/ansible-core reqs to development dependencies

---

docs/source/release_notes.rst
minimum-constraints-develop.txt
minimum-constraints-install.txt
plugins/module_utils/common.py
requirements-develop.txt
tests/unit/test_common.py

The immutable-views package is still referenced in the `minimum-constraints-install.txt` file because it is still an indirect dependency of the zhmcclient package at this point. It will also be replaced with immutabledict in a future zhmcclient release, and by that time, the indirect dependency in this repo here also needs to be updated.
Note: There is a slight inconsistency in this PR related to the change - ideally this PR should wait until zhmcclient 1.24 with support for immutabledict has been released.

Replaced immutable-view with immutabledict package

---

minimum-constraints-develop.txt
requirements-develop.txt

1.9: Cleaned up pydantic/-core package dependencies

---

.github/workflows/test.yml
changelogs/fragments/coveralls.yaml

Added retries for sending coverage data to the coveralls.io
