.travis.yml, os_setup.sh
=> Fixed Travis CI runs

.travis.yml, README.rst, docs/intro.rst, os_setup.sh
=> Docs: Fixed links to Ansible documentation

.travis.yml, README.rst, os_setup.sh
=> Docs: Added link to full docs on RTD to README.

docs/changes.rst
=> Updated change log for 0.2.0 release.

.gitignore, .travis.yml, Makefile, docs/gen/common_return_values.rst, docs/gen/list_of_all_modules.rst, docs/gen/zhmc_hba_module.rst, docs/gen/zhmc_nic_module.rst, docs/gen/zhmc_partition_module.rst, docs/gen/zhmc_virtual_function_module.rst
The generated module doc files are now checked in. There is a check in place in the Travis CI run as to whether they are up to date. I verified that an out-of-date module source file causes the Travis run to fail.
This PR is ready for review and merge.
=> Fixes #9: Fixed missing module docs files.

dev-requirements.txt, minimum-constraints.txt, requirements.txt
This PR is on top of PR #15 and supersedes it.
=> Updated package requirements and min.constraints

CODE_OF_CONDUCT.md
=> Add 1.4 of Contributor Covenent Code of Conduct

docs/changes.rst, minimum-constraints.txt, requirements.txt
=> Upgrade zhmcclient requirement to 0.15.0

docs/changes.rst
=> Updated change log for 0.3.0 release.

docs/changes.rst
=> Started 0.4.0 release.

README.rst, docs/conf.py, docs/intro.rst, setup.cfg
=> Rename z Systems family to IBM Z

docs/changes.rst, zhmc_ansible_modules/utils/__init__.py, zhmc_ansible_modules/zhmc_hba.py, zhmc_ansible_modules/zhmc_nic.py, zhmc_ansible_modules/zhmc_partition.py, zhmc_ansible_modules/zhmc_virtual_function.py
=> Fixes #31: Fixed rejection of 'type' property for Partitions

docs/gen/zhmc_partition_module.rst, playbooks/get_facts.yml, tests/function/test_func_partition.py, tests/unit/test_partition.py, zhmc_ansible_modules/zhmc_partition.py
=> Fixes #32: Added support for gathering partition + child facts

docs/changes.rst
=> Updated change log for 0.4.0 release.

Makefile
=> Fixes #44: Fix empty package version in Makefile

.travis.yml, Makefile, dev-requirements.txt, minimum-constraints.txt, requirements.txt
=> Makefile and package dep sync with python-zhmcclient

Makefile, docs/changes.rst
=> Some fixes in Makefile

Makefile, remove_duplicate_setuptools.py
=> Fixed ImportError for dist_info by removing duplicate setuptools

docs/gen/zhmc_hba_module.rst, docs/gen/zhmc_nic_module.rst, docs/gen/zhmc_partition_module.rst, docs/gen/zhmc_storage_group_attachment_module.rst, docs/gen/zhmc_storage_group_module.rst, docs/gen/zhmc_storage_volume_module.rst, docs/gen/zhmc_virtual_function_module.rst, zhmc_ansible_modules/zhmc_storage_group.py
=> Fixes #52: Fixed SG example in module docs to provide reqd props

Makefile
=> Improvements in Makefile

zhmc_ansible_modules/utils/__init__.py
=> Added log() function to _utils module

dev-requirements.txt, minimum-constraints.txt, requirements.txt
=> Updated requirements and min versions

docs/gen/list_of_all_modules.rst, docs/gen/zhmc_crypto_attachment_module.rst, docs/gen/zhmc_hba_module.rst, docs/gen/zhmc_nic_module.rst, docs/gen/zhmc_partition_module.rst, docs/gen/zhmc_storage_group_attachment_module.rst, docs/gen/zhmc_storage_group_module.rst, docs/gen/zhmc_storage_volume_module.rst, docs/gen/zhmc_virtual_function_module.rst, playbooks/attach_crypto_1.yml, playbooks/attach_crypto_2.yml, playbooks/attach_crypto_3.yml, playbooks/create_partition_crypto.yml, playbooks/detach_crypto.yml, playbooks/facts_crypto.yml, zhmc_ansible_modules/zhmc_crypto_attachment.py
=> Added support for crypto attachment to partition

docs/gen/list_of_all_modules.rst, docs/gen/zhmc_cpc_module.rst, playbooks/facts_cpc.yml, playbooks/set_cpc.yml, zhmc_ansible_modules/zhmc_cpc.py
Has been tested manually.
Ready for review and use.
=> Fixes #82: Added support for managing CPCs

Makefile, docs/changes.rst, zhmc_ansible_modules/zhmc_cpc.py
Note: This PR is on top of PR #90.
=> Fixes #87: Excluded DeprecationWarning from validate check

docs/changes.rst
=> Start 0.7.0

docs/changes.rst
=> Start 0.6.1

docs/changes.rst
Target of this PR is 0.6.1, because 0.6.0 is already released.
=> Fixed change log of 0.6.0

docs/changes.rst
=> Fixed change log of 0.6.0 (roll forward from 0.6.1)

zhmc_ansible_modules/zhmc_crypto_attachment.py
=> Added info to error on missing crypto adapters

docs/changes.rst
=> Release 0.7.0

docs/changes.rst
=> Start 0.8.0

docs/changes.rst
=> Start 0.9.0

tests/end2end/test_zhmc_partition.py, tests/end2end/utils.py
=> Cleaned up end2end test for zhmc_partition

Makefile, docs/gen/list_of_all_modules.rst, docs/gen/zhmc_user_module.rst, playbooks/facts_user.yml, tests/end2end/test_zhmc_user.py, zhmc_ansible_modules/zhmc_user.py
=> Fixes #117: Added zhmc_user module

docs/changes.rst, docs/gen/zhmc_user_module.rst, zhmc_ansible_modules/zhmc_user.py
Only description and change log updates, no review needed.
=> Fixed zhmc_user description and change log

docs/changes.rst
=> Start 0.8.1

docs/changes.rst, zhmc_ansible_modules/zhmc_adapter.py
Rolls back PR #142 into 0.8.1.
=> 0.8: Fixed AttributeError in zhmc_adapter when creating a Hipersockets adapter

docs/changes.rst
=> Release 0.8.1

docs/changes.rst, zhmc_ansible_modules/zhmc_adapter.py
Verified with originator that the fix works. No further review needed.
=> Fixed AttributeError in zhmc_adapter when creating a Hipersockets adapter

docs/changes.rst, plugins/modules/zhmc_nic.py
=> Fixed ParameterError raised when creating NICs on CNA adapter ports

docs/changes.rst
See change log: https://github.com/zhmcclient/zhmc-ansible-modules/blob/release_0.8.2/docs/changes.rst
=> Release 0.8.2

docs/changes.rst
=> Start 0.8.3

docs/gen/common_return_values.rst, docs/gen/modules_support.rst, docs/gen/zhmc_adapter_module.rst, docs/gen/zhmc_cpc_module.rst, docs/gen/zhmc_crypto_attachment_module.rst, docs/gen/zhmc_hba_module.rst, docs/gen/zhmc_nic_module.rst, docs/gen/zhmc_partition_module.rst, docs/gen/zhmc_storage_group_attachment_module.rst, docs/gen/zhmc_storage_group_module.rst, docs/gen/zhmc_storage_volume_module.rst, docs/gen/zhmc_user_module.rst, docs/gen/zhmc_virtual_function_module.rst, plugins/modules/zhmc_adapter.py, plugins/modules/zhmc_cpc.py, plugins/modules/zhmc_crypto_attachment.py, plugins/modules/zhmc_hba.py, plugins/modules/zhmc_nic.py, plugins/modules/zhmc_partition.py, plugins/modules/zhmc_storage_group.py, plugins/modules/zhmc_storage_group_attachment.py, plugins/modules/zhmc_storage_volume.py, plugins/modules/zhmc_user.py, plugins/modules/zhmc_virtual_function.py
=> Improved module documentation

README.md
=> Readme: Added doc link to dev version on master branch

docs/gen/zhmc_adapter_module.rst, docs/gen/zhmc_cpc_module.rst, docs/gen/zhmc_crypto_attachment_module.rst, docs/gen/zhmc_hba_module.rst, docs/gen/zhmc_nic_module.rst, docs/gen/zhmc_partition_module.rst, docs/gen/zhmc_storage_group_attachment_module.rst, docs/gen/zhmc_storage_group_module.rst, docs/gen/zhmc_storage_volume_module.rst, docs/gen/zhmc_virtual_function_module.rst
=> 0.8: Updated docs to latest templates

docs/changes.rst, plugins/modules/zhmc_nic.py
=> zhmc_nic: Updated definition of NIC properties to z15 and some z14 changes

docs/changes.rst, zhmc_ansible_modules/zhmc_storage_group.py, zhmc_ansible_modules/zhmc_storage_volume.py
=> 0.8: Fixed percent-encoding in 'zhmc_storage_group' and 'zhmc_storage_volume'

docs/changes.rst, playbooks/get_cpc_io.md.j2, playbooks/get_cpc_io.yml, tests/function/test_func_partition.py, tests/unit/test_partition.py, zhmc_ansible_modules/zhmc_cpc.py, zhmc_ansible_modules/zhmc_partition.py
Roll forward into master is needed.
=> 0.8: Improvements in cpc and partition modules

docs/source/index.rst, docs/source/intro.rst
=> Added Introduction section back in

Makefile, docs/source/conf.py
Minimal change, no review needed.
=> Fixed issues with sanity test in docs conf.py

Makefile, docs/source/conf.py
**Note:** This PR is on top of PR #188. Review only the delta.
=> Getting collection version from single source

galaxy.yml
=> Multiple changes to galaxy.xml.

docs/source/intro.rst
Editorial change - No review needed
=> Made wording in intro section consistent with README

README.md, galaxy.yml
README page for this PR: https://github.com/zhmcclient/zhmc-ansible-modules/blob/andy/update-readme/README.md
=> Updated README to fix syntax issues & badge links; Updated galaxy description

.gitignore
=> 0.8: Excluded 1.0 files from Git

.travis.yml
=> 0.8: Removed outdated Travis config elements

.travis.yml, dev-requirements.txt, docs/intro.rst, minimum-constraints.txt, requirements.txt
This PR rolls back PR #199 into 0.8.3.
No further review needed.
=> 0.8: Added support for Python 3.9

.travis.yml
=> 0.8: Fixed pypy in Travis

.travis.yml, Makefile
=> Added make doccheck again

docs/changes.rst
Please approve the release of version 0.8.3 to Pypi.
**Note: This PR is on top of PR #223 so review only the delta (last commit)**
=> Release 0.8.3

Makefile
=> Fixed make dependencies for module RST files

playbooks/attach_crypto.yml, playbooks/attach_crypto_byname.yml, playbooks/create_hipersockets.yml, playbooks/create_partition.yml, playbooks/create_partition_full.yml, playbooks/delete_hipersockets.yml, playbooks/delete_partition.yml, playbooks/delete_storage_group.yml, playbooks/delete_storage_volume.yml, playbooks/detach_crypto.yml, playbooks/facts_adapter.yml, playbooks/facts_cpc.yml, playbooks/facts_crypto.yml, playbooks/facts_partition.yml, playbooks/set_adapter.yml, playbooks/set_cpc.yml, playbooks/set_matched_adapter.yml
=> Cleaned up example playbooks

docs/changes.rst
=> Start 0.8.4

.github/workflows/pages.yml
Signed-off-by: Andreas Maier <andreas.r.maier@gmx.de>
=> fix #2 for gh-pages

.github/workflows/pages.yml, Makefile
=> Moved docs publishing entirely into pages workflow

.github/workflows/pages.yml
=> pages.yml: Fixed rsync command; removed install; editorial changes

.gh-pages-exclude, .gitignore, Makefile
=> Changed doctrees exclusion; fixed gitignore

docs/development.rst, docs/installation.rst
This is also the final test whether the versioned docs build shows changes from PRs.
=> Docs: Fixed collection name + final docs update test

.gh-pages-exclude, .github/workflows/pages.yml
=> Fixed exclusion of .doctrees

.github/workflows/pages.yml, README.md, docs/index.rst
=> fixed links of test and pages badges on readme page

.gitignore, Makefile, docs/conf.py, docs/development.rst, galaxy.yml
=> Add a local docs build target.

galaxy.yml
=> Excluded docs_build,.github from Galaxy archive

docs/release_notes.rst
=> Fixed change log heading levels

docs/changes.rst, setup.cfg
=> 0.8: Increased development status to Production/Stable

docs/development.rst
=> Fixed development section in docs to new docs build

docs/modules/zhmc_adapter.rst, docs/modules/zhmc_cpc.rst, docs/modules/zhmc_crypto_attachment.rst, docs/modules/zhmc_hba.rst, docs/modules/zhmc_nic.rst, docs/modules/zhmc_partition.rst, docs/modules/zhmc_storage_group.rst, docs/modules/zhmc_storage_group_attachment.rst, docs/modules/zhmc_storage_volume.rst, docs/modules/zhmc_user.rst, docs/modules/zhmc_virtual_function.rst, docs/templates/module.rst.j2
This PR updates the module template from the master version in the ibm_zos_core repo, and applies all pending changes listed in issue #275.
See commit messages for details.
=> Update module template from ibm_zos_core and apply pending changes

docs/changes.rst, docs/intro.rst, setup.cfg
=> 0.8: Fixed Python versions

README.md, docs/index.rst
=> Added note that 1.0.0 is not released yet

.github/workflows/pages.yml, .github/workflows/tags.yml, docs/conf.py
Need to merge this to try it out.
=> Support for dev tag automation in docs build

.github/workflows/tags.yml
Needs to be merged to try it out.
=> Next attempt for dev tag automation in docs build

.github/workflows/tags.yml
Need to merge it to try it out
=> Attempt #3 for dev tag automation in docs build

.github/workflows/tags.yml
=> Attempt #4 for dev tag automation in docs build

docs/development.rst
Since this is a trivial fix, I am merging this to test out the automatic docs update.
=> Fixed remaining changes.rst in dev section

README.md
=> Fixed remaining changes.html on readme page

README.md, docs/index.rst
=> Fixed links to Z, LinuxONE, Installation on README page

README.rst, docs/intro.rst
Rolls back PR #299 into 0.8.4. No review needed.
=> 0.8: Fixed links to Z/LinuxOne and clarified docs on README page

README.rst
=> 0.8: Minor updates to badges on readme page

README.md
=> Added galaxy badge with version

.github/workflows/docs.yml, README.md, docs/conf.py, docs/development.rst
=> Renamed pages.yml to docs.yml

docs/source/development.rst
=> Updated releasing/starting sections for docs

docs/source/modules/zhmc_adapter.rst, docs/source/modules/zhmc_cpc.rst, docs/source/modules/zhmc_crypto_attachment.rst, docs/source/modules/zhmc_hba.rst, docs/source/modules/zhmc_nic.rst, docs/source/modules/zhmc_partition.rst, docs/source/modules/zhmc_storage_group.rst, docs/source/modules/zhmc_storage_group_attachment.rst, docs/source/modules/zhmc_storage_volume.rst, docs/source/modules/zhmc_user.rst, docs/source/modules/zhmc_virtual_function.rst, docs/templates/module.rst.j2
See the discussion point in issue #309.
=> Support in module template for hiding private input parms

Makefile
=> Fixed make clobber by adding docs_build dir

README.md, docs/ansible_content.rst, docs/source/conf.py, docs/source/development.rst, docs/source/index.rst, docs/source/installation.rst, docs/source/modules.rst, docs/source/playbooks.rst, docs/source/requirements.rst, docs/source/requirements_managed.rst
=> Updated terminology for the collection

CODE_OF_CONDUCT.md, tools/os_setup.sh
=> Added copyright/license to all relevant files

.github/workflows/docs.yml, README.md, docs/ansible_content.rst, docs/source/conf.py, docs/source/index.rst, docs/source/release_notes.rst, galaxy.yml
=> Changed next version to 0.9.0

.github/workflows/docs.yml, README.md, docs/source/conf.py, docs/source/index.rst, docs/source/release_notes.rst, galaxy.yml
Please approve the release of version 0.9.0 to Ansible Galaxy.
**Note: This PR is on top of PR #323**
=> Release 0.9.0 to Ansible Galaxy

README.md
=> 0.9.0: Fixed link titles in README file

Makefile, galaxy.yml
=> 0.9.0: Added README to Galaxy archive; added Galaxy token

README.rst, docs/changes.rst, docs/intro.rst
=> Fixed galaxy version

.github/workflows/test.yml
=> Removed schedule event

setup.cfg
=> Fixed python_requires

setup.cfg
=> Fixed python_requires #2

.github/workflows/docs.yml, docs/source/conf.py
No review needed - this can only be tried out after it is merged.
=> Changed docs build approach

docs/source/conf.py, docs/source/development.rst
Can only be tested after being merged, so no review.
=> Updated developer docs for changed doc build; other docs build improvements

docs/source/release_notes.rst, galaxy.yml
=> Start 0.9.1

.github/workflows/docs.yml, docs/source/conf.py, docs/source/development.rst, docs/source/release_notes.rst, galaxy.yml
Rolls back PRs #335 and #336 into 0.9.1.
=> 0.9: Changed docs build approach and dev docs; other docs build improvements

.github/workflows/test.yml, docs/source/development.rst
=> Fixed updating of stable branch in test.yml workflow

.github/workflows/test.yml, docs/source/development.rst
=> 0.9: Fixed updating of stable branch in test.yml workflow

README.md
=> Added RH Certified section back in to README file

docs/source/conf.py, docs/source/release_notes.rst, galaxy.yml
For changes, see release notes in this PR.
=> Release 0.9.1

docs/source/release_notes.rst, galaxy.yml
=> Start 0.9.2

docs/source/development.rst, docs/source/release_notes.rst
Rolls back PR #348 into 0.9.2.
=> 0.9: Fixes  and improvements in development docs

docs/source/development.rst, docs/source/release_notes.rst
=> Fixes  and improvements in development docs

.github/workflows/docs.yml, Makefile, dev-requirements.txt, docs/source/conf.py, docs/source/development.rst, docs/source/release_notes.rst, minimum-constraints.txt, tools/version.py
Can only be tested after merged - no review needed.
=> Fixed possible inconsistency in docs build between stable/master branches

.github/workflows/docs.yml, Makefile, dev-requirements.txt, docs/source/conf.py, docs/source/development.rst, docs/source/release_notes.rst, minimum-constraints.txt, tools/version.py
Rolls back PR #351 into 0.9.2.
=> 0.9: Fixed possible inconsistency in docs build between stable/master branches

docs/source/development.rst
Rolls back PR #353 into 0.9.2.
=> 0.9: Updated the dev section for releasing/starting a version

docs/source/development.rst
=> Updated the dev section for releasing/starting a version

docs/source/conf.py
Can only be tested when merging it, so no review needed.
=> Fixed docs build failure for whitelisted branches

docs/source/conf.py
Rolls back PR #355 into 0.9.2.
=> 0.9: Fixed docs build failure for whitelisted branches

docs/source/conf.py
Can be tested only when merged -> no review needed.
=> Fixed missing whitelisted branches in docs

docs/source/conf.py
Rolls back PR #357 into 0.9.2.
=> 0.9: Fixed missing whitelisted branches in docs

docs/source/release_notes.rst, plugins/modules/zhmc_cpc.py
=> zhmc_cpc: Clarified CPC can be in any mode; added classic mode write props

dev-requirements.txt, docs/source/release_notes.rst
=> Mitigated coveralls issue with HTTP status 422

.github/workflows/test.yml, dev-requirements.txt, minimum-constraints.txt
See commit messages for details.
=> Recent updates from cookiecutter-python project

docs/ansible_content.rst, docs/source/modules.rst
This is a copy of PR #372 with review comments resolved.
=> Updates for unified IBM Z collection documentation

.github/workflows/test.yml, dev-requirements.txt, docs/source/conf.py, docs/source/release_notes.rst, minimum-constraints.txt, tests/sanity/ignore-2.9.txt
=> Fixed issues related to Ansible sanity test

.github/workflows/test.yml, tests/sanity/ignore-2.9.txt
=> Test: Enabled Python 3.6 tests to have Pylint run during sanity check

.github/workflows/test.yml
=> Moved scheduled test to SUN 04:00 UTC

docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Increased minimum version of zhmcclient to 0.29.0

.github/workflows/test.yml, Makefile, dev-requirements.txt, tests/sanity/ignore-2.9.txt
Multiple commits to address these issues. See commit messages for details.
=> Fixed sanity test issues with Ansible 2.9

.github/workflows/test.yml, dev-requirements.txt, minimum-constraints.txt, tests/sanity/ignore-2.9.txt
=> Upgraded pylint/astroid to latest to address sanity issue

Makefile, tests/sanity/ignore-2.9.txt
=> Skipped 2nd chunk of problematic pylint checks for Ansible 2.9

dev-requirements.txt, docs/source/release_notes.rst, tests/sanity/ignore-2.11.txt
=> Fixed doc build issue and sanity check issue

README.md
Signed-off-by: Vance Morris <vmorris@us.ibm.com>
=> Fixes #398 - Correct broken link in README.md

docs/source/installation.rst, docs/source/release_notes.rst
=> Docs: Stated that ansible-core 2.11 is supported

docs/source/release_notes.rst, galaxy.yml
Please approve the release of version 0.9.2 to Ansible Galaxy.
=> Release 0.9.2

docs/source/release_notes.rst, minimum-constraints.txt, plugins/modules/zhmc_adapter.py, plugins/modules/zhmc_cpc.py, plugins/modules/zhmc_crypto_attachment.py, plugins/modules/zhmc_hba.py, plugins/modules/zhmc_nic.py, plugins/modules/zhmc_partition.py, plugins/modules/zhmc_storage_group.py, plugins/modules/zhmc_storage_volume.py, plugins/modules/zhmc_user.py, plugins/modules/zhmc_virtual_function.py, requirements.txt, tests/function/test_func_partition.py
No review needed (if it succeeds, see PR #413 this PR is now on top of).
=> Increased the minimum version of zhmcclient to 0.31.0

.github/workflows/docs.yml, docs/source/release_notes.rst
=> Fixed error during automatic docs build when two PRs are merged

docs/source/release_notes.rst
=> Test 1 for ghpages fix

docs/source/release_notes.rst
=> Test 2 for ghpages fix

docs/source/release_notes.rst
=> Test 3a for ghpages fix

docs/source/release_notes.rst
=> Test 3b for ghpages fix

docs/source/release_notes.rst
=> Test 3 cleanup

docs/source/conf.py, docs/source/release_notes.rst
=> Docs: Building for all versions since 0.9.0 and master

docs/source/conf.py
=> Docs: Fixed error in previous commit

.github/workflows/docs.yml, .github/workflows/test.yml, docs/source/release_notes.rst, galaxy.yml
Please approve the release of version 0.10.0 to Ansible Galaxy.
=> Release 0.10.0

docs/source/release_notes.rst, galaxy.yml
=> Start 0.9.3

docs/source/release_notes.rst, galaxy.yml
=> Release 0.9.3

docs/source/release_notes.rst, galaxy.yml
=> Start 0.10.1

docs/source/release_notes.rst, galaxy.yml
=> Start 1.0.0

docs/source/release_notes.rst, plugins/modules/zhmc_adapter.py, plugins/modules/zhmc_hba.py, plugins/modules/zhmc_nic.py, plugins/modules/zhmc_partition.py, plugins/modules/zhmc_storage_group.py, plugins/modules/zhmc_storage_volume.py, plugins/modules/zhmc_user.py, plugins/modules/zhmc_virtual_function.py, tests/function/test_func_partition.py
=> Fixed new Pylint issues reported by Pylint 2.9

docs/source/release_notes.rst, plugins/modules/zhmc_adapter.py, plugins/modules/zhmc_hba.py, plugins/modules/zhmc_nic.py, plugins/modules/zhmc_partition.py, plugins/modules/zhmc_storage_group.py, plugins/modules/zhmc_storage_volume.py, plugins/modules/zhmc_user.py, plugins/modules/zhmc_virtual_function.py, tests/function/test_func_partition.py
Rolls back PR #438 into 0.10.1.
=> 0.10: Fixed new Pylint issues reported by Pylint 2.9

bindep.txt, meta/runtime.yml, requirements.txt
Rolls back PR #440 into 0.10.1.
=> 0.10: Added new meta files: bindep.txt, meta/runtime.yml

bindep.txt, meta/runtime.yml, requirements.txt
=> Added new meta files: bindep.txt, meta/runtime.yml

docs/source/release_notes.rst, plugins/modules/zhmc_adapter.py, plugins/modules/zhmc_crypto_attachment.py, plugins/modules/zhmc_partition.py, plugins/modules/zhmc_storage_group.py, plugins/modules/zhmc_user.py, tests/function/test_func_partition.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tools/version.py
=> Fixed new Pylint issues reported by Pylint 2.10

docs/source/release_notes.rst, plugins/modules/zhmc_adapter.py, plugins/modules/zhmc_crypto_attachment.py, plugins/modules/zhmc_partition.py, plugins/modules/zhmc_storage_group.py, plugins/modules/zhmc_user.py, tests/function/test_func_partition.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tools/version.py
Rolls back PR #443 into 0.10.1.
=> 0.10: Fixed new Pylint issues reported by Pylint 2.10

docs/source/release_notes.rst, plugins/modules/zhmc_adapter.py, plugins/modules/zhmc_cpc.py, plugins/modules/zhmc_crypto_attachment.py, plugins/modules/zhmc_hba.py, plugins/modules/zhmc_nic.py, plugins/modules/zhmc_partition.py, plugins/modules/zhmc_storage_group.py, plugins/modules/zhmc_storage_group_attachment.py, plugins/modules/zhmc_storage_volume.py, plugins/modules/zhmc_user.py, plugins/modules/zhmc_virtual_function.py
=> Improved handling of exceptions when creation of zhmcclient.Session fails

Makefile, dev-requirements.txt, minimum-constraints.txt
=> Falling back to Pylint 2.6 to address new 'consider-using-f-string' issue

.github/workflows/test.yml, dev-requirements.txt, docs/source/installation.rst, docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Added support for Python 3.10

docs/source/installation.rst
=> Expressed supported Ansible versions with ansible package version

docs/source/installation.rst, docs/source/release_notes.rst, requirements.txt, tests/sanity/ignore-2.12.txt
=>  Added support for Ansible 5.0

docs/source/modules/zhmc_lpar.rst
No review needed, just a rebuild.
=> Updated RST files after updating zhmc_lpar module

docs/source/modules.rst, docs/source/modules/zhmc_cpc_list.rst, plugins/modules/zhmc_cpc_list.py, tests/function/test_func_cpc_list.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.9.txt
This PR implements option C described in issue #469. I think we should go ahead with this option. Ready for review and merge.
=> Added zhmc_cpc_list module

docs/source/modules/zhmc_partition.rst, plugins/module_utils/common.py, plugins/modules/zhmc_partition.py
=> Fixed starting/stopping of partitions

docs/source/modules/zhmc_partition.rst, plugins/module_utils/common.py, plugins/modules/zhmc_partition.py
Rolls back PR #476 into 0.10.1.
=> 0.10: Fixed starting/stopping of partitions

docs/source/release_notes.rst, galaxy.yml
=> Release 0.10.1

docs/source/modules.rst, docs/source/modules/zhmc_lpar_list.rst, plugins/module_utils/common.py, plugins/modules/zhmc_lpar_list.py, tests/function/test_func_lpar_list.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.9.txt
See commit message for details.
This PR implements option C described in issue https://github.com/zhmcclient/zhmc-ansible-modules/issues/469. I think we should go ahead with this option. Ready for review and merge.
=> Added zhmc_lpar_list module

docs/source/modules/zhmc_cpc_list.rst
=> Updated generated docs for cpc_list module

docs/source/modules/zhmc_lpar.rst, plugins/module_utils/common.py, plugins/modules/zhmc_lpar.py, tests/function/test_func_lpar.py
=> zhmc_lpar: Added state=active and force; Fixes; Changed state values

requirements.txt
=> Pulling zhmcclient from master

minimum-constraints.txt, requirements.txt
=> Using published zhmcclient 1.2.0

docs/source/release_notes.rst
=> UPdated change log for previous commit

docs/source/release_notes.rst, galaxy.yml
=> Start 1.1.0

docs/source/release_notes.rst, galaxy.yml
=> Start 1.0.1

docs/source/development.rst, docs/source/release_notes.rst, galaxy.yml
=> Fixed missing required tag in metadata

docs/source/release_notes.rst, galaxy.yml
This fix release fixes a requirement specific to AutomationHub.
=> Release 1.0.1

.github/workflows/test.yml, Makefile, docs/source/development.rst, docs/source/release_notes.rst, plugins/module_utils/common.py, plugins/modules/zhmc_cpc_list.py, plugins/modules/zhmc_lpar.py, plugins/modules/zhmc_lpar_list.py, tests/function/test_func_cpc_list.py, tests/function/test_func_lpar.py, tests/function/test_func_lpar_list.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.9.txt
=> 1.0: Resolved sanity test issues reported on AutomationHub; added 'make check'; Described the publishing to AutomationHub

docs/source/release_notes.rst, galaxy.yml
=> Release 1.0.2

.github/workflows/test.yml, Makefile, docs/source/development.rst, docs/source/release_notes.rst, galaxy.yml, plugins/module_utils/common.py, plugins/modules/zhmc_cpc_list.py, plugins/modules/zhmc_lpar.py, plugins/modules/zhmc_lpar_list.py, tests/function/test_func_cpc_list.py, tests/function/test_func_lpar.py, tests/function/test_func_lpar_list.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.9.txt
=> Roll forward AutomationHub fixes from 1.0.2

docs/source/release_notes.rst, galaxy.yml
=> Start 1.0.3

Makefile, docs/source/development.rst
Rolls back PR #501 into 1.0.3.
=> 1.0: Changed upload to AutomationHub to be make driven; fixed dev detection

Makefile, docs/source/development.rst
=> Changed upload to AutomationHub to be make driven; fixed dev detection

README.md
=> Added badge for AutomationHub

docs/source/index.rst
=> Added link to the collection on AutomationHub

README.md, docs/source/index.rst
Rolls back PRs #503 and #504 into 1.0.3.
=> 1.0: Added badge for AutomationHub; Added link to the collection on AutomationHub

docs/source/release_notes.rst, plugins/modules/zhmc_user.py
Rolls back PR #509 into 1.0.3.
=> 1.0: zhmc_user: Fixed incorrect attrs/methods; Made check mode consistent

Makefile, docs/source/release_notes.rst, tests/end2end/test_zhmc_partition.py, tests/end2end/test_zhmc_user.py, tests/end2end/utils.py
Rolls back PR #510 into 1.0.3.
=> 1.0: Fixed end2end test concept and testcases

README.md, docs/source/development.rst, docs/source/index.rst, docs/source/installation.rst, docs/source/versioning.rst
=> Fixed links in docs and README

docs/source/modules/zhmc_user.rst, docs/source/release_notes.rst, plugins/modules/zhmc_user.py, tests/end2end/test_zhmc_user.py
See commit message for details
=> Added support for specifying user roles as input in zhmc_user module

.github/workflows/test.yml, docs/source/release_notes.rst, requirements.txt
See commit message for details.
=> Sanity test: Fixed CryptographyDeprecationWarning on Python 3.6

.github/workflows/test.yml, docs/source/release_notes.rst, requirements.txt
Rolls back PR #520 into 1.0.3.
=> 1.0: Sanity test: Fixed CryptographyDeprecationWarning on Python 3.6

.github/workflows/docs.yml, .github/workflows/test.yml, docs/source/release_notes.rst, galaxy.yml
Please approve the release of version 1.1.0
=> Release 1.1.0

docs/source/release_notes.rst, galaxy.yml
=> Start 1.2.0

docs/source/release_notes.rst, galaxy.yml
=> Start 1.1.1

docs/source/modules/zhmc_user.rst
No review needed. The module docs was out of date.
=> Updated module docs for zhmc_user module

docs/source/modules.rst, docs/source/modules/zhmc_partition_list.rst, docs/source/release_notes.rst, plugins/modules/zhmc_partition_list.py, tests/function/test_func_partition_list.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.9.txt
=> Added support for new 'zhmc_partition_list' Ansible module

docs/source/release_notes.rst, tests/sanity/ignore-2.13.txt
=> Added support for Ansible 6.0.0

docs/source/release_notes.rst, tests/sanity/ignore-2.13.txt
=> 1.1: Added support for Ansible 6.0.0

docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Changed zhmcclient back to 1.3

minimum-constraints.txt, requirements.txt
=> Upgraded zhmcclient to released 1.3.2 version

docs/source/modules.rst, docs/source/modules/zhmc_user_role.rst, docs/source/modules/zhmc_user_role_list.rst, docs/source/release_notes.rst, plugins/modules/zhmc_user_role.py, plugins/modules/zhmc_user_role_list.py, tests/end2end/mocked_z14_classic.yaml, tests/end2end/mocked_z14_dpm.yaml, tests/end2end/test_zhmc_user_role.py, tests/end2end/test_zhmc_user_role_list.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.9.txt
For details, see the commit message
The end2end test succeeded on a z15 in classic mode and on a z15 in DPM mode.
=> Added new modules for user roles

tests/end2end/test_zhmc_cpc_list.py, tests/end2end/test_zhmc_lpar_list.py, tests/end2end/test_zhmc_partition.py, tests/end2end/test_zhmc_partition_list.py, tests/end2end/test_zhmc_password_rule.py, tests/end2end/test_zhmc_password_rule_list.py, tests/end2end/test_zhmc_user.py, tests/end2end/test_zhmc_user_role.py, tests/end2end/test_zhmc_user_role_list.py
=> Renamed end2end test functions; added no unmanaged parm

tests/end2end/test_zhmc_user_role.py
=> Disabled debug in end2end test zhmc_user_role

tests/end2end/test_zhmc_cpc_list.py
=> Fixed end2end test for CPCs

docs/source/release_notes.rst, plugins/module_utils/common.py
=> 1.1: Fixed that every module invocation created additional log handler

docs/source/release_notes.rst, plugins/modules/zhmc_lpar_list.py, plugins/modules/zhmc_partition_list.py, tests/end2end/test_zhmc_lpar_list.py, tests/end2end/test_zhmc_partition_list.py
=> Support for lpar/partition_list on 2.13 HMCs

docs/source/modules/zhmc_lpar_list.rst, docs/source/modules/zhmc_partition_list.rst
=> Updated generated RST files from previous commit

docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Increased zhmcclient to 1.3.3

docs/source/release_notes.rst, galaxy.yml
=> Release 1.1.1

docs/source/release_notes.rst, galaxy.yml
=> Start 1.1.2

docs/source/release_notes.rst, plugins/module_utils/common.py, plugins/modules/zhmc_partition.py, tests/end2end/mocked_hmc_z14.yaml, tests/end2end/test_zhmc_partition.py, tests/function/test_func_partition.py, tests/unit/test_partition.py
=> zhmc_partition: Fixed check mode; fixed 'boot-storage-volume-name' in result

dev-requirements.txt, docs/source/release_notes.rst, minimum-constraints.txt
=> Fixed flake8 AttributeError by pinning importlib-metadata

dev-requirements.txt, docs/source/release_notes.rst, minimum-constraints.txt
Rolls back PR #568 into 1.1.2.
=> 1.1: Fixed flake8 AttributeError by pinning importlib-metadata

dev-requirements.txt, minimum-constraints.txt, requirements.txt
=> Moved importlib-metadata to requirements.txt

dev-requirements.txt, minimum-constraints.txt, requirements.txt
Rolls back PR #571 into 1.1.2.
=> 1.1: Moved importlib-metadata to requirements.txt

docs/source/modules/zhmc_lpar.rst, docs/source/release_notes.rst, plugins/modules/zhmc_lpar.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt
=> Added 'reset_clear', 'reset_normal' to zhmc_lpar module

docs/source/modules.rst, docs/source/modules/zhmc_adapter_list.rst, docs/source/release_notes.rst, plugins/modules/zhmc_adapter_list.py, tests/end2end/test_zhmc_adapter_list.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.9.txt
For just reviewing the functionality, look at the module docstring: https://github.com/zhmcclient/zhmc-ansible-modules/blob/andy/adapter-list/plugins/modules/zhmc_adapter_list.py#L35
=> Added zhmc_adapter_list module

docs/source/release_notes.rst, plugins/modules/zhmc_adapter.py
=> Made zhmc_adapter module tolerant against unconfigured FICON adapters

docs/source/release_notes.rst, plugins/modules/zhmc_user.py
=> Made zhmc_user module tolerant against unusual cases

tests/unit/test_hba.py, tests/unit/test_nic.py, tests/unit/test_partition.py, tests/unit/test_virtual_function.py
=> Resolved new issues reported by flake8 5.0

docs/source/modules/zhmc_adapter.rst, docs/source/modules/zhmc_lpar.rst
=> Updated module rst files

.github/workflows/test.yml
=> Moved develop before install in GitHub Actions test

.github/workflows/test.yml, Makefile, dev-requirements.txt, docs/source/development.rst, docs/source/installation.rst, docs/source/release_notes.rst, meta/runtime.yml, minimum-constraints.txt, requirements.txt, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.9.txt
=> Adjusted and enabled Ansible sanity tests

.github/workflows/test.yml, dev-requirements.txt, docs/source/development.rst, docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Added tests for Python 3.11

.github/workflows/test.yml
=> Accomodated switch of Actions to Ubuntu 22.04

docs/source/release_notes.rst, galaxy.yml
Please approve the release of version 1.2.0
=> Release 1.2.0

docs/source/release_notes.rst, galaxy.yml
=> Start 1.3.0

docs/source/release_notes.rst, galaxy.yml
=> Start 1.2.1

docs/source/development.rst
=> Fixed development section in docs

docs/source/development.rst
=> Fixed development docs (2)

docs/source/release_notes.rst, galaxy.yml
=> Release 1.2.1

dev-requirements.txt
=> Unpinned voluptuous on Python 2.7

dev-requirements.txt, docs/source/release_notes.rst
=> Fixed sphinx-versions local fork to be PEP 440 compliant

.github/workflows/test.yml, docs/source/release_notes.rst
=> Addressed issues in test workflow reported by Github Actions

.github/workflows/test.yml, Makefile, ansible-constraints.txt, dev-requirements.txt, minimum-constraints.txt, requirements.txt
=> Added 'check_reqs' make target; updated reqs

.github/workflows/publish.yml, docs/source/development.rst
=> fix dev docs / upgrade actions modules

.github/workflows/test.yml
=> Restructured the definition of the weekly full tests

Makefile, docs/source/release_notes.rst
=> Added package dependency checking for the remaining Python-based tools

dev-requirements.txt, docs/source/release_notes.rst, minimum-constraints.txt
=> Increased minimum versions of pip, setuptools, wheel to more recent versions

Makefile, dev-requirements.txt, docs/source/release_notes.rst, minimum-constraints.txt
=> Changed pip install to use python -m pip install

.github/workflows/test.yml, .safety-policy.yml, Makefile, dev-requirements.txt, minimum-constraints.txt
=>  Added running safety, ignoring any issues

.safety-policy.yml, Makefile, ansible-constraints.txt, dev-requirements.txt, docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Addressed issues reported by safety

.github/workflows/test.yml, minimum-constraints.txt, requirements.txt
=> Fixed sanity test on Python>3.7 with minimum package level; Changed test envs

.safety-policy.yml
=> Fixed new safety issues from 3/17

.whitesource
=> Enabled Whitesource Mend scanning

SECURITY.md
=> Added security policy; enabled private viulnerability reporting

docs/source/release_notes.rst, plugins/modules/zhmc_user_role.py
Note, in order to see the full improvement, zhmcclient PR https://github.com/zhmcclient/python-zhmcclient/pull/1136 is needed. However, for functional purposes, that PR is not needed.
=> Improved performance of zhmc_user_role for state=facts

docs/source/modules/zhmc_user.rst, docs/source/release_notes.rst, plugins/modules/zhmc_user.py
=> Performance improvements for zhmc_user module with state=facts

docs/source/release_notes.rst, minimum-constraints.txt, plugins/modules/zhmc_adapter.py, plugins/modules/zhmc_cpc.py, plugins/modules/zhmc_hba.py, plugins/modules/zhmc_lpar.py, plugins/modules/zhmc_nic.py, plugins/modules/zhmc_partition.py, plugins/modules/zhmc_password_rule.py, plugins/modules/zhmc_storage_group.py, plugins/modules/zhmc_storage_volume.py, plugins/modules/zhmc_user.py, plugins/modules/zhmc_user_role.py, plugins/modules/zhmc_virtual_function.py, tests/sanity/ignore-2.15.txt, tests/unit/test_hba.py, tests/unit/test_nic.py, tests/unit/test_partition.py, tests/unit/test_virtual_function.py
=> Added support for Ansible version 8

docs/source/release_notes.rst, minimum-constraints.txt, plugins/modules/zhmc_adapter.py, plugins/modules/zhmc_cpc.py, plugins/modules/zhmc_hba.py, plugins/modules/zhmc_lpar.py, plugins/modules/zhmc_nic.py, plugins/modules/zhmc_partition.py, plugins/modules/zhmc_password_rule.py, plugins/modules/zhmc_storage_group.py, plugins/modules/zhmc_storage_volume.py, plugins/modules/zhmc_user.py, plugins/modules/zhmc_user_role.py, plugins/modules/zhmc_virtual_function.py, tests/sanity/ignore-2.15.txt, tests/unit/test_hba.py, tests/unit/test_nic.py, tests/unit/test_partition.py, tests/unit/test_virtual_function.py
Rolls back PR #674 into 1.3.1.
=> 1.3: Added support for Ansible version 8

.github/workflows/test.yml, docs/source/release_notes.rst, tools/os_setup.sh
Rolls back PR #676 into 1.3.1.
=> 1.3: Circumvented removal of Python 2.7 support in setup-python action

docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Increased version of cryptography package to 41.0.0 on Python >=3.7

docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
Rolls back PR #678 into 1.3.1.
=> 1.3: Increased version of cryptography package to 41.0.0 on Python >=3.7

docs/source/installation.rst
=> Added Ansible 8 to the list of supported versions in docs

docs/source/installation.rst, docs/source/release_notes.rst, galaxy.yml
=> Release 1.3.1

docs/source/modules.rst, docs/source/modules/zhmc_console.rst, docs/source/release_notes.rst, plugins/modules/zhmc_console.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.9.txt
=> Added zhmc_console module

.github/workflows/test.yml, docs/source/development.rst, docs/source/release_notes.rst
=> Dropped testing with Python 2.7 on macOS

docs/source/development.rst, docs/source/release_notes.rst
=> Dropped testing with Python 2.7 on macOS, part 2

docs/source/development.rst, docs/source/release_notes.rst, galaxy.yml
=> Release 1.4.0

docs/source/release_notes.rst, galaxy.yml
=> Start 1.4.1

docs/source/release_notes.rst, galaxy.yml
=> Start 1.5.0

.safety-policy.yml, docs/source/release_notes.rst, minimum-constraints.txt
=> Fixed safety issues from 6/23

.safety-policy.yml, docs/source/release_notes.rst, minimum-constraints.txt
Rolls back PR #694 into 1.4.1.
=> 1.4: Fixed safety issues from 6/23

docs/source/release_notes.rst, plugins/modules/zhmc_nic_list.py
Rolls back PR #692 into 1.4.1.
=> 1.4: Fixed zhmc_nic_list

plugins/modules/zhmc_nic_list.py
The prior PR went in with auto-merge even though it failed. This PR adds the rest that was missing.
=> 1.4: Fixed zhmc_nic_list - part2

.safety-policy.yml
=> Fixed safety issues 7/5/2023

.safety-policy.yml
=> 1.4: Fixed safety issues 7/5/2023

dev-requirements.txt, minimum-constraints.txt
=> Added antsibull-docs-parser to dependencies

docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Increased minimum version of cryptography package to 41.0.2

.safety-policy.yml, docs/source/release_notes.rst
=> Fixed safety issues from 7/17

docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Picked up zhmcclient version 1.9.0 to get fixes

Makefile, docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Fixed PyYAML install issue with Cython 3

docs/source/modules/zhmc_adapter.rst, docs/source/modules/zhmc_adapter_list.rst, docs/source/modules/zhmc_console.rst, docs/source/modules/zhmc_cpc.rst, docs/source/modules/zhmc_cpc_list.rst, docs/source/modules/zhmc_crypto_attachment.rst, docs/source/modules/zhmc_hba.rst, docs/source/modules/zhmc_lpar.rst, docs/source/modules/zhmc_lpar_list.rst, docs/source/modules/zhmc_nic.rst, docs/source/modules/zhmc_nic_list.rst, docs/source/modules/zhmc_partition.rst, docs/source/modules/zhmc_partition_list.rst, docs/source/modules/zhmc_password_rule.rst, docs/source/modules/zhmc_password_rule_list.rst, docs/source/modules/zhmc_session.rst, docs/source/modules/zhmc_storage_group.rst, docs/source/modules/zhmc_storage_group_attachment.rst, docs/source/modules/zhmc_storage_volume.rst, docs/source/modules/zhmc_user.rst, docs/source/modules/zhmc_user_list.rst, docs/source/modules/zhmc_user_role.rst, docs/source/modules/zhmc_user_role_list.rst, docs/source/modules/zhmc_virtual_function.rst
=> Updated generated docs files with new Ansible docs tools

Makefile, docs/source/modules/zhmc_console.rst, docs/source/modules/zhmc_cpc.rst, docs/source/release_notes.rst, minimum-constraints.txt, plugins/modules/zhmc_console.py, plugins/modules/zhmc_cpc.py, requirements.txt
=> Support for upgrading HMC and SE firmware

minimum-constraints.txt, requirements.txt
=> Increased cryptography to 41.0.3 on py>=3.7

minimum-constraints.txt, requirements.txt
=> 1.5: Increased cryptography to 41.0.3 on py>=3.7

Makefile, docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Used zhmcclient 1.10.0

docs/source/release_notes.rst, galaxy.yml
=> Start 1.7.0

docs/source/release_notes.rst, galaxy.yml
=> Start 1.6.1

.safety-policy.yml, minimum-constraints.txt
=> Fixed safety issues from 2023-08-26

.safety-policy.yml, minimum-constraints.txt
=> 1.6: Fixed safety issues from 2023-08-26

.safety-policy.yml, docs/source/release_notes.rst
=> Fixed safety issues from 2023-09-06

.safety-policy.yml, docs/source/release_notes.rst
Rolls back PR #737 into 1.6.1.
=> 1.6: Fixed safety issues from 2023-09-06

docs/source/modules/zhmc_console.rst, docs/source/modules/zhmc_cpc.rst, docs/source/release_notes.rst
=> Docs: Clarified FW upgrades to existing bundle level

Makefile, docs/source/release_notes.rst
=> Clarified coverage handling by make

tests/end2end/test_zhmc_adapter_list.py
=> Fixed flake8 issue in test_zhmc_adapter_list.py from previous PR

docs/source/modules.rst, docs/source/modules/zhmc_ldap_server_definition.rst, docs/source/modules/zhmc_ldap_server_definition_list.rst, docs/source/release_notes.rst, minimum-constraints.txt, plugins/modules/zhmc_ldap_server_definition.py, plugins/modules/zhmc_ldap_server_definition_list.py, requirements.txt, tests/end2end/mocked_hmc_z14.yaml, tests/end2end/test_zhmc_ldap_server_definition.py, tests/end2end/test_zhmc_ldap_server_definition_list.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.9.txt
=> Added support for LDAP Server Definitions

docs/source/release_notes.rst, plugins/modules/zhmc_session.py, plugins/modules/zhmc_user_role.py, tests/end2end/test_zhmc_partition.py, tests/end2end/test_zhmc_session.py, tests/end2end/test_zhmc_user.py
I ran the end2end tests on T224, and they now succeed.
=> Support for user role permissions based on groups; Fixed end2end tests

docs/source/modules/zhmc_console.rst, docs/source/modules/zhmc_cpc.rst, docs/source/modules/zhmc_session.rst
=> Re-generated module .rst files that were out of sync - pt.2

docs/source/modules/zhmc_session.rst, docs/source/release_notes.rst, plugins/modules/zhmc_session.py, plugins/modules/zhmc_user_role.py, tests/end2end/test_zhmc_adapter_list.py, tests/end2end/test_zhmc_partition.py, tests/end2end/test_zhmc_session.py, tests/end2end/test_zhmc_user.py
Rolls back PR #750 into 1.6.1.
=> 1.6: Support for user role permissions based on groups; Fixed end2end tests

docs/source/modules/zhmc_console.rst, docs/source/modules/zhmc_cpc.rst
=> 1.6: Re-generated module .rst files that were out of sync

docs/source/release_notes.rst, minimum-constraints.txt, plugins/modules/zhmc_adapter.py, requirements.txt, tests/end2end/mocked_hmc_z14.yaml, tests/end2end/test_zhmc_adapter.py
**Note: This PR is on top of PR #758 - review only the commit with the same title as this PR**
End2end tests with T224 were successful.
=> zhmc_adapter: Changed match to have priority over name

docs/source/release_notes.rst, plugins/modules/zhmc_adapter.py, tests/end2end/test_zhmc_adapter.py
Rolls back PR #760 into 1.6.1.
=> 1.6: zhmc_adapter: Changed match to have priority over name

.github/workflows/test.yml, docs/source/release_notes.rst
=> Added check for doc .rst files being up to date in test workflow

CHANGELOG.rst, docs/source/release_notes.rst
Rolls back PR #764 into 1.6.1.
=> 1.6: Added CHANGELOG.rst in a compatible way

docs/source/modules/zhmc_partition.rst, docs/source/release_notes.rst, plugins/modules/zhmc_partition.py, tests/end2end/test_zhmc_partition.py, tests/function/test_func_partition.py
Has been end2end tested on T224.
=> Fixed partition boot from storage volume

docs/source/modules/zhmc_partition.rst, docs/source/release_notes.rst, plugins/modules/zhmc_partition.py, tests/end2end/test_zhmc_partition.py, tests/function/test_func_partition.py
Rolls back PR #765 into 1.6.1.
=> 1.6: Fixed partition boot from storage volume

docs/source/modules/zhmc_crypto_attachment.rst, docs/source/release_notes.rst, plugins/modules/zhmc_crypto_attachment.py
Rolls back PR #773 into 1.6.1.
=> 1.6: Fixed zhmc_crypto_attachment parameters

docs/source/release_notes.rst, plugins/module_utils/common.py, plugins/modules/zhmc_hba.py, plugins/modules/zhmc_nic.py, plugins/modules/zhmc_partition.py, plugins/modules/zhmc_virtual_function.py, tests/end2end/test_zhmc_partition.py, tests/function/test_func_partition.py
Rolls back PR #642 into 1.6.1.
=> 1.6: Fixed that partitions in 'paused' status could not be stopped

tests/sanity/ignore-2.10.txt
=> Fixed sanity test issue with raise-missing-from

docs/source/modules/zhmc_lpar.rst, docs/source/release_notes.rst, plugins/module_utils/common.py, plugins/modules/zhmc_lpar.py, tests/function/test_func_lpar.py
=> Added parameters to LPAR load/activate

tests/sanity/ignore-2.10.txt
=> 1.6: Fixed sanity test issue with raise-missing-from

docs/source/release_notes.rst, galaxy.yml
=> Release 1.6.1

docs/source/release_notes.rst, galaxy.yml
=> Release 1.7.0

docs/source/release_notes.rst, galaxy.yml
=> Start 1.8.0

docs/source/release_notes.rst, galaxy.yml
=> Start 1.7.1

README.md, docs/source/release_notes.rst
=> Fixed galaxy link on README page

README.md, docs/source/release_notes.rst
Rolls back PR #788 into 1.7.1.
=> 1.7: Fixed galaxy link on README page

.github/workflows/test.yml, Makefile, docs/source/release_notes.rst, galaxy.yml
=> Removed doc/test files from collection package

Makefile, docs/source/release_notes.rst
=> Development: Added package level to .done files

.github/workflows/test.yml, Makefile, dev-requirements.txt, docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Added support for Python 3.12; Other fixes

docs/source/release_notes.rst, plugins/modules/zhmc_adapter_list.py, plugins/modules/zhmc_cpc_list.py, plugins/modules/zhmc_hba.py, plugins/modules/zhmc_ldap_server_definition_list.py, plugins/modules/zhmc_lpar.py, plugins/modules/zhmc_lpar_list.py, plugins/modules/zhmc_nic.py, plugins/modules/zhmc_nic_list.py, plugins/modules/zhmc_partition.py, plugins/modules/zhmc_partition_list.py, plugins/modules/zhmc_password_rule_list.py, plugins/modules/zhmc_session.py, plugins/modules/zhmc_storage_group.py, plugins/modules/zhmc_storage_group_attachment.py, plugins/modules/zhmc_storage_volume.py, plugins/modules/zhmc_user_list.py, plugins/modules/zhmc_user_role_list.py, plugins/modules/zhmc_virtual_function.py
=> Logging: Fixed the result name in the log message for module success

docs/source/release_notes.rst, plugins/modules/zhmc_adapter_list.py, plugins/modules/zhmc_cpc_list.py, plugins/modules/zhmc_hba.py, plugins/modules/zhmc_ldap_server_definition_list.py, plugins/modules/zhmc_lpar.py, plugins/modules/zhmc_lpar_list.py, plugins/modules/zhmc_nic.py, plugins/modules/zhmc_nic_list.py, plugins/modules/zhmc_partition.py, plugins/modules/zhmc_partition_list.py, plugins/modules/zhmc_password_rule_list.py, plugins/modules/zhmc_session.py, plugins/modules/zhmc_storage_group.py, plugins/modules/zhmc_storage_group_attachment.py, plugins/modules/zhmc_storage_volume.py, plugins/modules/zhmc_user_list.py, plugins/modules/zhmc_user_role_list.py, plugins/modules/zhmc_virtual_function.py
Rolls back PR #805 into 1.7.1.
=> 1.7: Logging: Fixed the result name in the log message for module success

docs/source/modules/zhmc_lpar.rst, docs/source/release_notes.rst, plugins/module_utils/common.py, plugins/modules/zhmc_lpar.py
=> Fixed docs for zhmc_lpar module with state=loaded/active and code cleanup

.github/workflows/test.yml
=> Reduced number of normal test envs from 18 to 11

docs/source/release_notes.rst, galaxy.yml
=> Release 1.7.1

dev-requirements.txt, minimum-constraints.txt
=> Added ruamel dependency to fix issue with it on Python 3.6

dev-requirements.txt, minimum-constraints.txt
=> 1.7: Added ruamel dependency to fix issue with it on Python 3.6

docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Addressed safety issues up to 2023-11-05

docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> 1.7: Addressed safety issues up to 2023-11-05

.safety-policy.yml, minimum-constraints.txt, requirements.txt, tests/function/test_func_lpar.py
=> Fixed missing 'operating-mode' in Image Profile setup for mocked LPAR fct tests

docs/source/modules/zhmc_lpar.rst, plugins/modules/zhmc_lpar.py, tests/end2end/test_zhmc_lpar.py, tests/end2end/utils.py, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt
=> Added end2end test for zhmc_lpar module; Clarified zhmc_lpar return description

docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
Will be needed by OS message support.
=> Use zhmcclient 1.12.0 as a minimum

Makefile, ansible-constraints.txt, docs/source/development.rst, docs/source/installation.rst, docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt, tests/sanity/ignore-2.16.txt
=> Added support for Ansible 9

.safety-policy.yml, docs/source/release_notes.rst, minimum-constraints.txt
=> Addressed safety issues up to 2023-11-26

Makefile, docs/source/development.rst, docs/source/installation.rst
=> Improved description of supported Ansible/Python versions and sanity test run

docs/source/release_notes.rst, galaxy.yml
=> Release 1.7.2

docs/source/release_notes.rst, galaxy.yml
=> Start 1.7.3

docs/source/modules/zhmc_console.rst, docs/source/modules/zhmc_cpc.rst, docs/source/release_notes.rst, plugins/modules/zhmc_console.py, plugins/modules/zhmc_cpc.py
- Added upgrade_timeout parameter to zhmc_console and zhmc_cpc modules
- Added entry for change in release_notes.rst
Signed-off by Abhiram Santhosh <abhiram.santhosh1@ibm.com>
=> Added upgrade_timeout parameter to zhmc_console and zhmc_cpc modules

docs/source/release_notes.rst, galaxy.yml
=> Release 1.7.3

docs/source/release_notes.rst, galaxy.yml
=> Start 1.7.4

.safety-policy.yml, docs/source/release_notes.rst
=> Safety issues 2024-01-03

.safety-policy.yml, docs/source/release_notes.rst
Rolls back PR #847 into 1.7.4.
=> 1.7: Safety issues 2024-01-03

.safety-policy.yml, ansible-constraints.txt, docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Safety issues 2024-01-08

.safety-policy.yml, ansible-constraints.txt, docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
Rolls back PR #856 into 1.7.4.
=> 1.7: Safety issues 2024-01-08

docs/source/release_notes.rst, tests/end2end/test_zhmc_cpc_list.py
=> Fixed error in end2end test for zhmc_cpc_list module

docs/source/modules/zhmc_storage_group.rst, docs/source/release_notes.rst, plugins/modules/zhmc_storage_group.py
=> Fixed KeyError in 'zhmc_storage_group' module for non-FCP groups

docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
This change is needed for PR #858
=> Increased zhmcclient to 1.13.0

minimum-constraints.txt
=> Removed commented-out unused packages in minimum-constraints.txt (pt.2)

minimum-constraints.txt
Rolls back PR #875 into 1.7.4.
=> 1.7: Removed unused packages from minimum-constraints.txt

docs/source/release_notes.rst, galaxy.yml
=> Release 1.7.4

AUTHORS.md, Makefile, docs/source/development.rst, docs/source/release_notes.rst
=> Support for creating AUTHORS.md file

.github/workflows/test.yml, docs/source/release_notes.rst
=> Fixed pipdeptree call in test workflow

.github/workflows/test.yml, Makefile, dev-requirements.txt, minimum-constraints.txt
=> Added ansible-lint to check_reqs and reduced py vers; Added py310/min to tests

.github/workflows/test.yml, docs/source/release_notes.rst
Rolls back PR #882 into 1.7.5.
=> 1.7: Fixed pipdeptree call in test workflow

README.md, docs/source/conf.py, docs/source/index.rst
No review needed - this is a follow-up to PR #879
=> Fixed copyright statements with year-year range, pt.2

tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt
=> Improved wording and fixed typo in 'forgotten-debug-statement' ignore

docs/source/release_notes.rst, galaxy.yml
=> Start 1.7.5

.github/workflows/test.yml, Makefile, ansible-constraints.txt, dev-requirements.txt, docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Fixed Sphinx / sphinxcontrib-applehelp version issue

Makefile, ansible-constraints.txt, dev-requirements.txt, docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
Rolls back PR #890 into 1.7.5.
=> 1.7: Fixed Sphinx / sphinxcontrib-applehelp version issue

minimum-constraints.txt, requirements.txt
=> Increased zhmcclient to 1.13.1

docs/source/modules/zhmc_lpar_list.rst, docs/source/release_notes.rst, plugins/modules/zhmc_lpar_list.py, tests/end2end/test_zhmc_lpar_list.py
=> Support for additional_properties in zhmc_lpar_list module

ansible-constraints.txt, docs/source/release_notes.rst, galaxy.yml
=> Release 1.8.0

Makefile, galaxy.yml, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt
Needs to go into 12.8.0 on AutomationHub.
=> Release 1.8.0 fix: Fix AutomationHub import - this is 1.8.0 on Hub

docs/source/release_notes.rst, galaxy.yml
=> Release 1.8.1 - AutomationHub import fixes

docs/source/release_notes.rst, galaxy.yml
=> Start 1.8.2

docs/source/release_notes.rst, galaxy.yml
=> Start 1.9.0

.safety-policy.yml, docs/source/release_notes.rst
=> Fixed safety issues up to 2024-01-26

.safety-policy.yml, docs/source/release_notes.rst
Rolls back PR #906 into 1.8.2.
=> 1.8: Fixed safety issues up to 2024-01-26

Makefile, docs/source/release_notes.rst, minimum-constraints.txt, plugins/modules/zhmc_lpar_list.py, requirements.txt, tests/end2end/test_zhmc_lpar_list.py, tests/end2end/test_zhmc_partition_list.py
Rolls back PR #905 into 1.8.2.
=> 1.8: Fixed performance issue with zhmc_lpar/partition_list 

.github/workflows/test.yml, docs/source/release_notes.rst
=> Increased versions of GitHub Actions plugins to node 20

Makefile, minimum-constraints.txt, requirements.txt
Rolls back PR #911 into 1.8.2.
=> 1.8: Used released version of zhmcclient 1.13.3

Makefile, minimum-constraints.txt, requirements.txt
=> Used released version of zhmcclient 1.13.3

docs/source/release_notes.rst, galaxy.yml
=> Release 1.8.2

docs/source/release_notes.rst, galaxy.yml
=> Start 1.8.3

docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Fixed dependabot issues

docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
Rolls back PR #923 into 1.8.3.
=> 1.8: Fixed dependabot issues

.safety-policy.yml, docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> Fixed safety issues up to 2024-02-18

.safety-policy.yml, docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
Rolls back PR #926 into 1.8.3.
=> 1.8: Fixed safety issues up to 2024-02-18

docs/source/release_notes.rst, plugins/modules/zhmc_partition.py
Rolls back PR #933 into 1.8.3.
=> 1.8: Fixed AttributeError in ensure_iso_mount function of zhmc_partition

.github/workflows/test.yml, ansible-constraints.txt
Rolls back PR #931 into 1.8.3.
=> 1.8/fix jinja2

AUTHORS.md, docs/source/release_notes.rst, galaxy.yml
=> Release 1.8.3

docs/source/release_notes.rst, galaxy.yml
=> Start 1.8.4

.safety-policy-all.yml, .safety-policy-install.yml, Makefile, docs/source/release_notes.rst, minimum-constraints-install.txt, minimum-constraints.txt
=> Use minimum versions for safety run on dependencies for install

.github/workflows/test.yml, Makefile, docs/source/development.rst, docs/source/release_notes.rst
=> Safety run for all dependencies must succeed for releases

.safety-policy-install.yml, docs/source/release_notes.rst
=> Safety issues up to 3/25

.safety-policy.yml, docs/source/release_notes.rst
Rolls back PR #944 into 1.8.4.
=> 1.8: Safety issues up to 3/25

.safety-policy-install.yml, docs/source/release_notes.rst, minimum-constraints-install.txt, minimum-constraints.txt, requirements.txt
=> Fixed missing deps of typer package; Fixed safety issues up to 3/31

.safety-policy.yml, docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
Rolls back PR #946 into 1.8.4.
=> 1.8: Fixed missing deps of typer package; Fixed safety issues up to 3/31

.github/workflows/test.yml, docs/source/release_notes.rst
=> Fixed macos version used in test workflow for py35/36/37

.github/workflows/test.yml, Makefile, dev-requirements.txt, docs/source/release_notes.rst, minimum-constraints.txt, plugins/modules/zhmc_partition.py
=> Added Bandit checker

.github/workflows/test.yml
=> Fixed macos-12 issue for package level ansible

.github/workflows/test.yml
Rolls back PR #954 into 1.8.4.
=> 1.8: Fixed macos-12 issue for package level ansible

.github/workflows/test.yml, docs/source/installation.rst, docs/source/release_notes.rst
Rolls back PR #961 into 1.8.4.
=> 1.8: Dropped test runs on Python 3.5

.github/workflows/publish.yml, .github/workflows/test.yml, docs/source/installation.rst, docs/source/release_notes.rst
**Note:** This PR is on top of #961 - merge only after that one is merged.
=> Added 'safety' / 'bandit' to the 'publish' workflow

.github/workflows/test.yml, docs/source/development.rst, docs/source/installation.rst, docs/source/release_notes.rst
**Note:** This PR is on top of #961 - merge only after that one is merged.
=> Documented Mend & Dependabot review when releasing

.safety-policy-install.yml, docs/source/release_notes.rst, minimum-constraints-install.txt, minimum-constraints.txt, requirements.txt
=> Fixed safety issues up to 2024-05-18

.safety-policy.yml, docs/source/release_notes.rst, minimum-constraints.txt, requirements.txt
=> 1.8: Fixed safety issues up to 2024-05-18

.safety-policy-install.yml
=> safety issue with jinja2

.safety-policy.yml
Rolls back PR #968 into 1.8.4.
=> 1.8: Safety issue with jinja2

.github/workflows/publish.yml, .github/workflows/test.yml, docs/source/release_notes.rst
=> Upgraded Actions plugins to no longer use deprecated node 16

.safety-policy-install.yml, docs/source/release_notes.rst
=> Fixed safety issues up to 6/16

galaxy.yml
No review needed - was done incorrectly when starting the new version.
=> Fixed dev version of the collection

.safety-policy.yml, docs/source/release_notes.rst
Rolls back PR #980 into 1.8.4.
=> 1.8: Fixed safety issues up to 6/16

.github/workflows/test.yml, Makefile, dev-requirements.txt, docs/source/release_notes.rst, requirements.txt
=> Added tests for Python 3.13-beta.1

Makefile, minimum-constraints-install.txt, requirements.txt, tests/end2end/mocked_hmc_z16.yaml, tests/end2end/mocked_inventory.yaml, tests/end2end/mocked_vault.yaml
=> Added end2end mock file for z16; Used zhmcclient 1.17.0 (dev)

.safety-policy-install.yml, docs/source/release_notes.rst, minimum-constraints-install.txt, requirements.txt
=> Fixed safety issues up to 2024-06-24

Makefile, docs/source/conf.py, docs/source/release_notes.rst
=> Reduced versions in generated documentation

tests/end2end/mocked_hmc_z14.yaml, tests/end2end/mocked_hmc_z16.yaml
=> Fixed HMC mock files

Makefile, docs/source/release_notes.rst
=> Dev: Error message cleanup in Makefile; Fixed make clobber for .done files

.safety-policy-all.yml, .safety-policy-install.yml
=> Clarified comments in safety policy files

Makefile
=> Removed remaining Python 2 check in Makefile in check_reqs

docs/source/release_notes.rst, tests/end2end/mocked_hmc_z14.yaml, tests/end2end/mocked_hmc_z16.yaml
=> Test: Added virtual storage resource objects to the mocked end2end test envs

Makefile, docs/source/release_notes.rst
=> Fixed coverage data for module_utils files

docs/source/installation.rst, docs/source/release_notes.rst
=> Docs: Added installing a development version

docs/source/release_notes.rst
=> Docs: Fixed Sphinx warning in release notes

docs/source/bibliography.rst, docs/source/modules/zhmc_user_pattern_list.rst, plugins/modules/zhmc_user_pattern_list.py
=> Fixed link to Java regular expressions in zhmc_user_pattern_list

README.md
=> Fixed badge link in README.md file

README.md, docs/source/development.rst
=> Added more checkers we use to README and Testing docs

Makefile, docs/source/release_notes.rst, minimum-constraints-install.txt, requirements.txt
=> Used released zhmcclient 1.17.0

docs/source/release_notes.rst, galaxy.yml
=> Start 1.9.1

docs/source/release_notes.rst, galaxy.yml
=> Start 1.10.0

Makefile, docs/source/release_notes.rst, galaxy.yml, tests/config.yml
=> Fixed sanity test on AutomationHub

Makefile, docs/source/release_notes.rst, galaxy.yml, tests/config.yml
Rolls back PR #1038 into 1.9.1.
=> 1.9: Fixed sanity test on AutomationHub

docs/source/release_notes.rst, galaxy.yml
=> Start 1.9.2

docs/source/release_notes.rst, minimum-constraints-install.txt
=> Fixed safety issues up to 20024-07-19

docs/source/release_notes.rst, minimum-constraints-install.txt
Rolls back PR #1043 into 1.9.2.
=> 1.9: Fixed safety issues up to 20024-07-19

ansible-constraints.txt, requirements.txt
=> Fixed safety issues up to 20024-07-19 - fix

docs/source/development.rst
=> Docs: Minor fixes in 'Releasing a version' section

ansible-constraints.txt, requirements.txt
Rolls back PR #1045 into 1.9.2.
=> 1.9: Fixed safety issues up to 20024-07-19 - fix

docs/source/release_notes.rst, galaxy.yml
=> Removed collections directory from dist archive

docs/source/release_notes.rst, galaxy.yml
=> Synced authors and description in collection metadata

README.md, docs/source/development.rst
=> Mentioned bandit vulnerability check in list of tests

Makefile, docs/source/release_notes.rst
=> Cleaned up preparation of sanity test in Makefile

.github/workflows/test.yml, Makefile, docs/source/development.rst
=> Clarified that supported OS for development are only Linux/macOS

docs/source/release_notes.rst, minimum-constraints-develop.txt, minimum-constraints-install.txt, requirements-develop.txt, requirements.txt
=> Fixed safety issues up to 20024-07-28

docs/source/release_notes.rst, minimum-constraints-develop.txt, minimum-constraints-install.txt, requirements-develop.txt, requirements.txt
Rolls back PR #1056 into 1.9.2.
=> 1.9: Fixed safety issues up to 20024-07-28

Makefile, docs/source/release_notes.rst, minimum-constraints-develop.txt, requirements-develop.txt
=> Fixed check_reqs and added psutil as dep; Addressed safety issues

Makefile, docs/source/release_notes.rst, minimum-constraints-develop.txt, requirements-develop.txt
Rolls back PR #1060 into 1.9.2.
=> 1.9: Fixed check_reqs and added psutil as dep; Addressed safety issues

Makefile, docs/source/release_notes.rst
=> Fixed removal of some files in Makefile

Makefile, docs/source/development.rst, docs/source/release_notes.rst
=> Dev: Relaxed the conditions when safety issues are tolerated

docs/source/development.rst
=> Fixed dependabot alerts term

docs/source/development.rst
=> Fixed release instructions on closing milestone

docs/source/release_notes.rst, minimum-constraints-install.txt, requirements-base.txt
=> Addressed safety issues

docs/source/release_notes.rst, minimum-constraints-install.txt, requirements-base.txt
Rolls back PR #1067 into 1.9.2.
=> 1.9: Addressed safety issues

docs/source/release_notes.rst, minimum-constraints-develop.txt, minimum-constraints-install.txt, requirements.txt
=> Increased zhmcclient to 1.18.0

.safety-policy-install.yml, docs/source/release_notes.rst
=> Fixed safety issues up to 2024-11-03

.safety-policy-install.yml, docs/source/release_notes.rst
Rolls back PR #1076 into 1.9.2.
=> 1.9: Fixed safety issues up to 2024-11-03

docs/source/release_notes.rst, minimum-constraints-install.txt, requirements.txt
=> Fixed safety issues up to 2024-11-21

docs/source/release_notes.rst, minimum-constraints-install.txt, requirements.txt
Rolls back PR #1083 into 1.9.2.
=> 1.9: Fixed safety issues up to 2024-11-21

.github/workflows/test.yml, Makefile, docs/source/bibliography.rst, docs/source/conf.py, docs/source/index.rst, docs/source/installation.rst, docs/source/playbooks.rst, docs/source/release_notes.rst, docs/source/requirements.rst
Rolls back PR #1085 into 1.9.2.
=> 1.9: Fixed broken/redirected links; Added linkcheck to test workflow

.github/workflows/test.yml, docs/source/release_notes.rst
=> Accomodated rollout of Ubuntu 24.04 on GitHub Actions

.github/workflows/test.yml, docs/source/release_notes.rst
Rolls back PR #1100 into 1.9.4.
=> 1.9: Accomodated rollout of Ubuntu 24.04 on GitHub Actions

.safety-policy-install.yml, docs/source/release_notes.rst, minimum-constraints-install.txt, requirements.txt
Rolls back PR #1102 into 1.9.4.
=> 1.9: Addressed safety issues up to 2024-12-29

docs/source/modules/zhmc_adapter.rst, docs/source/modules/zhmc_cpc.rst, docs/source/modules/zhmc_ldap_server_definition.rst, docs/source/modules/zhmc_lpar.rst, docs/source/modules/zhmc_nic.rst, docs/source/modules/zhmc_partition.rst, docs/source/modules/zhmc_password_rule.rst, docs/source/modules/zhmc_storage_group.rst, docs/source/modules/zhmc_storage_volume.rst, docs/source/modules/zhmc_user.rst, docs/source/modules/zhmc_user_pattern.rst, docs/source/modules/zhmc_user_role.rst
=> Update .rst files due to new formatting

docs/source/modules/zhmc_adapter.rst, docs/source/modules/zhmc_cpc.rst, docs/source/modules/zhmc_ldap_server_definition.rst, docs/source/modules/zhmc_lpar.rst, docs/source/modules/zhmc_nic.rst, docs/source/modules/zhmc_partition.rst, docs/source/modules/zhmc_password_rule.rst, docs/source/modules/zhmc_storage_group.rst, docs/source/modules/zhmc_storage_volume.rst, docs/source/modules/zhmc_user.rst, docs/source/modules/zhmc_user_pattern.rst, docs/source/modules/zhmc_user_role.rst
Rolls back PR #1105 into 1.9.4.
=> 1.9: Update .rst files due to new formatting

ansible-constraints.txt, docs/source/release_notes.rst, minimum-constraints-install.txt, requirements.txt
=> Safety issues up to 2025-01-29

ansible-constraints.txt, docs/source/release_notes.rst, minimum-constraints-install.txt, requirements.txt
Rolls back PR #1108 into 1.9.4.
=> 1.9: Safety issues up to 2025-01-29

docs/source/release_notes.rst, minimum-constraints-develop.txt
=> Fixed missing dependencies

docs/source/release_notes.rst, minimum-constraints-develop.txt
=> 1.9: Fixed missing dependencies

minimum-constraints-develop.txt
Rolls back PR #1112 into 1.9. No review needed.
=> 1.9: Fixed missing package dependencies for development (nltk)

docs/source/release_notes.rst, minimum-constraints-install.txt, requirements-base.txt
=> Fixed safety issues

docs/source/release_notes.rst, minimum-constraints-install.txt, requirements-base.txt
=> 1.9: Fixed safety issues

.github/workflows/test.yml, Makefile, docs/source/release_notes.rst
=> Added make targets platform&env; displayed in test workflow

ansible-constraints.txt, docs/source/release_notes.rst, minimum-constraints-develop.txt, minimum-constraints-install.txt, requirements-develop.txt, requirements.txt
=> Increased safety to 3.4.0 and updated its dependencies; Safety issues

ansible-constraints.txt, docs/source/release_notes.rst, minimum-constraints-develop.txt, minimum-constraints-install.txt, requirements-develop.txt, requirements.txt
=> 1.9: Increased safety to 3.4.0 and updated its dependencies; Safety issues

.github/workflows/test.yml, docs/source/release_notes.rst
=> 1.9: Tolerate linkcheck errors

.mailmap, AUTHORS.md, Makefile, docs/source/release_notes.rst
=> 1.9: Made order of names in AUTHORS.md consistent; added mailmap

docs/source/development.rst
This fixes a leftover from PR #1169
=> Dev: Fixed dev docs on tested ansible versions

.github/workflows/test.yml, ansible-constraints.txt, docs/source/development.rst, docs/source/release_notes.rst, minimum-constraints-develop.txt, requirements-develop.txt
=> Added Python 3.13 to tests

docs/source/release_notes.rst, tests/end2end/test_zhmc_partition.py
=> Speed up end2end test test_zhmc_partition_properties()

README.md, docs/source/release_notes.rst
=> Fixed Ansible Galaxy badge on readme page

docs/source/release_notes.rst, requirements-develop.txt
=> Circumvented safety issue with import of typer module

docs/source/release_notes.rst, plugins/modules/zhmc_nic.py, plugins/modules/zhmc_partition.py, tests/end2end/test_zhmc_partition.py
I performed the following tests:
* Manual tests with zhmc_nic and state=present,facts,absent against z16 and z17 CPCs
* Manual tests with zhmc_nic_list against z16 and z17 CPCs
=> Fixed issue with creating/updating OSA/HS NICs on z17

docs/source/release_notes.rst, minimum-constraints-install.txt, requirements.txt
=> Increased zhmcclient to 1.23.1

docs/source/release_notes.rst, minimum-constraints-develop.txt, minimum-constraints-install.txt, requirements-base.txt, requirements-develop.txt, requirements.txt
=> Cleaned up dependencies

minimum-constraints-develop.txt
=> Added missing dev dependency to 'distro'

minimum-constraints-develop.txt
=> 1.9: Added missing dev dependency to 'distro'

minimum-constraints-develop.txt
=> 1.9: Added pytokens package to minimum-constraints file for development

docs/source/development.rst
=> Docs: Improved verify step when releasing a new version

minimum-constraints-develop.txt, requirements-develop.txt
=> Cleaned up pydantic/-core package dependencies

changelogs/fragments/1225-changelog_rst.yaml, docs/source/modules/zhmc_cpc_capacity.rst, plugins/modules/zhmc_cpc_capacity.py, tests/end2end/test_zhmc_cpc_capacity.py
I tested the fix with the new end2end test function `test_zhmc_cpc_capacity_set()` on A224.
=> Fixed bug in zhmc_cpc_capacity where decreasing capacity resulted in TypeError

docs/source/modules/zhmc_cpc_capacity.rst, docs/source/release_notes.rst, plugins/modules/zhmc_cpc_capacity.py, tests/end2end/test_zhmc_cpc_capacity.py
=> 1.9: Fixed bug in zhmc_cpc_capacity where decreasing capacity resulted in TypeError

docs/source/development.rst
=> Fixed steps for starting a release
